/* ── Pipeline / Feed ────────────────────────────────────────────────────
   LOCK pipeline state (maxStep, feedSteps, feedAgents), feed renderer
   (feedAddEntry/Block/Sep), agent pills, topology pulse, setStep/play.
   Loaded after app.js — references globals declared there.
   ──────────────────────────────────────────────────────────────────────── */
// ── Pipeline steps ──
let maxStep = -1;

function updateAgentPills(i) {
  const pills = [
    // step 0: report selected, pipeline starting
    { hyp:['Running','chip-blue',30,'Analysing CTI · 14 TTPs queued'],               orch:['Running','chip-blue',50,'Routing tasks · pipeline initialised'],  data:['Running','chip-blue',50,'Connecting to Splunk ES…'],              ts:['Waiting','chip-gray',0,'Awaiting TTPs'],               dl:['Waiting','chip-gray',0,'Awaiting tradecraft notes'] },
    // step 1: TTPs loaded from upstream pipeline, hypothesis agent working
    { hyp:['Running','chip-blue',70,'Cross-referencing past hunts · 3 recalled'],     orch:['Running','chip-blue',70,'Routing tasks · 2 agents active'],        data:['Done','chip-green',100,'Splunk data ready · indices available'], ts:['Waiting','chip-gray',0,'Awaiting hypotheses'],          dl:['Waiting','chip-gray',0,'Awaiting tradecraft notes'] },
    // step 2: hypotheses generated by Hypothesis Agent
    { hyp:['Done','chip-green',100,'3 hypotheses generated · handed to Orchestrator'],orch:['Done','chip-green',100,'Hypotheses routed · pipeline continues'],   data:['Done','chip-green',100,'Splunk data available · CIM-normalised'], ts:['Review','chip-blue',80,'3 hypotheses ready for review'], dl:['Waiting','chip-gray',0,'Awaiting tradecraft notes'] },
    // step 3: tradecraft running
    { hyp:['Done','chip-green',100,'3 hypotheses generated · analyst notes applied'], orch:['Done','chip-green',100,'Hunt coordinated · all tasks routed'],     data:['Done','chip-green',100,'Splunk data available · CIM-normalised'], ts:['Active','chip-blue',100,'Querying Splunk ES · 59 hits'],  dl:['Running','chip-blue',40,'Awaiting tradecraft notes'] },
    // step 4: detection logic + rule validation (via tool)
    { hyp:['Done','chip-green',100,'3 hypotheses generated · analyst notes applied'], orch:['Done','chip-green',100,'Hunt coordinated · all tasks routed'],     data:['Done','chip-green',100,'Splunk data available · CIM-normalised'], ts:['Done','chip-green',100,'Tradecraft analysis complete'],  dl:['Active','chip-blue',90,'Generating rules · validating via RuleVal tool…'] },
  ];
  const s = pills[Math.min(i, pills.length - 1)];
  function set(id, [chip, cls, pct, status]) {
    const el = document.getElementById(id);
    if (!el) return;
    el.style.opacity = '1';
    document.getElementById(id + '-status').textContent = status;
    document.getElementById(id + '-fill').style.width = pct + '%';
    const c = document.getElementById(id + '-chip');
    c.textContent = chip; c.className = 'chip ' + cls; c.style.fontSize = '10px';
  }
  set('ap-orch', s.orch);
  set('ap-hyp',  s.hyp);  set('ap-data', s.data);
  set('ap-ts',   s.ts);   set('ap-dl',   s.dl);
}

// ── Live agent feed ──
const feedAgents = {
  hyp:  { icon:'💡', name:'Hypothesis' },
  orch: { icon:'🎛️', name:'Orchestrator' },
  data: { icon:'🗄️', name:'Data Eng' },
  ts:   { icon:'🧠', name:'Tradecraft' },
  dl:   { icon:'⚙️',  name:'Detection Logic' },
};
const feedPfx = { tool:'→', reason:'↳', done:'✓', warn:'⚠', runbook:'📖', env:'🏗️', rv:'✅', relay:'↗' };
const feedAgentColors = {
  orch: { bg:'rgba(59,130,246,.18)',  border:'#3b82f6' },
  hyp:  { bg:'rgba(20,184,166,.18)', border:'#14b8a6' },
  data: { bg:'rgba(99,102,241,.18)', border:'#6366f1' },
  ts:   { bg:'rgba(245,158,11,.18)', border:'#f59e0b' },
  dl:   { bg:'rgba(16,185,129,.18)', border:'#10b981' },
};
const feedBadgeLabels = { tool:'TOOL CALL', reason:'REASONING', done:'COMPLETE', warn:'WARNING', runbook:'RUNBOOK', env:'ENV CTX', rv:'RULE VALID', relay:'MSG' };

const feedSteps = {
  0: [
    { type:'tool',   agent:'orch', msg:'pipeline initialised for TH-2026-041 · CISA AA24-038A · dispatching agents' },
    { type:'relay',  agent:'orch', to:'data', msg:'initialise Splunk ES connection · confirm index availability across sysmon, windows, network, security' },
    { type:'tool',   agent:'data', msg:'authenticating to Splunk ES via service token · enumerating indices…' },
    { type:'relay',  agent:'data', to:'orch', msg:'connected · 4 indices confirmed · sysmon(7d) windows(30d) network(14d) security(90d) · CIM normalisation verified',
      detail:'Auth via service account token. All 4 indices ingested and CIM-normalised. Baseline window set to 30 days. Ready for query workload.' },
    { type:'relay',  agent:'orch', to:'hyp',  msg:'stand by — loading 14 TTPs from CISA AA24-038A upstream pipeline · pre-load environment topology to scope hypotheses' },
    { type:'relay',  agent:'hyp',  to:'orch', msg:'acknowledged · fetching environment topology now · will have context ready before gather phase begins' },
    { type:'env',    agent:'orch', msg:'get_topology() → 8 network segments · 10.0.0.0/8 scope · 2,412 endpoints · Tier-0 isolation active' },
    { type:'done',   agent:'orch', msg:'14 TTPs loaded · confidence scored · T1078.002(95%) T1570(87%) T1003.001(82%) · routing to Stage 1',
      detail:'Advisory signal strength scored across 14 TTPs. Top 3 candidates selected based on confidence score, Tier-0 asset exposure, and prior hunt signal. 3 TTPs flagged for analyst gate review before pipeline advances.' },
  ],
  1: [
    { type:'relay',  agent:'orch', to:'hyp',  msg:'begin parallel gather for T1078.002, T1570, T1003.001 · query past hunts, coverage checker, and runbooks simultaneously' },
    { type:'relay',  agent:'hyp',  to:'orch', msg:'acknowledged · starting parallel gather now · will report back per-TTP as results land' },
    { type:'tool',   agent:'hyp',  msg:'search_hunts("T1078.002") → 3 past hunts retrieved · TH-2026-038 overlaps on jsmith credential abuse' },
    { type:'tool',   agent:'hyp',  msg:'get_hunt("TH-2026-038") → lateral movement confirmed · CORP\\jsmith pivoted 9 hosts · analyst notes loaded' },
    { type:'tool',   agent:'hyp',  msg:'check_coverage("T1078.002") → 1 existing rule active · last triggered 4 days ago · possible detection gap' },
    { type:'relay',  agent:'hyp',  to:'orch', msg:'T1078.002 — prior confirmed hits in TH-2026-038 · existing rule stale (4 days) · need Tier-0 asset context before finalising scope' },
    { type:'env',    agent:'orch', msg:'get_asset("WIN-DC01") → Tier-0 Domain Controller · 10.0.1.10 · DC VLAN · CrowdStrike Falcon 7.1' },
    { type:'env',    agent:'orch', msg:'get_account("jsmith") → Corp Workstations segment · off-hours logon anomaly flagged · MFA enrolled' },
    { type:'relay',  agent:'orch', to:'hyp',  msg:'WIN-DC01 is Tier-0 · jsmith shows off-hours anomaly pattern matching TH-2026-038 window · elevate T1078.002 to top priority' },
    { type:'reason', agent:'hyp',  msg:'confidence on T1078.002 raised to 95% — off-hours logon + Tier-0 DC exposure confirmed',
      detail:'Prior hunt TH-2026-038 confirmed lateral movement via CORP\\jsmith credential abuse. Off-hours logon from 23:17–01:42 UTC maps directly to the current attack window. Existing coverage rule last hit 4 days ago — suggests actor may have shifted technique. Elevating confidence 87% → 95% and narrowing scope to DC VLAN (10.0.1.0/24).' },
    { type:'relay',  agent:'hyp',  to:'data', msg:'run EventCode 4769 TGS-REQ baseline · last 30 days · 5-minute buckets · flag DC VLAN segment' },
    { type:'tool',   agent:'data', msg:'querying Splunk ES · EventCode 4769 · 30-day window · CIM normalisation applied…' },
    { type:'relay',  agent:'data', to:'hyp',  msg:'baseline complete · 2.4M events in scope · mean 18,400 ev/hr · DC VLAN (10.0.1.0/24) flagged Tier-0 · 3σ spike threshold set',
      detail:'2,412,087 Kerberos TGS-REQ events over 30 days. Fields mapped: src_user, dest, ticket_encryption_type. Spike threshold = 3σ above per-account daily average. DC VLAN ACL anomaly: 3 workstation IPs accessed DC segment outside maintenance window.' },
    { type:'reason', agent:'orch', msg:'scope locked: T1078.002 · T1570 · T1003.001 · decision matrix complete · awaiting analyst gate approval',
      detail:'Decision matrix:\n• T1078.002 — conf 95%, Tier-0 DC exposure, off-hours anomaly → INCLUDE\n• T1570 — conf 87%, confirmed in TH-2026-038 (9 hosts pivoted) → INCLUDE\n• T1003.001 — conf 82%, LSASS pattern follows lateral movement chain → INCLUDE\nExcluded: T1558.003 (22% FP, CMDB filter not yet applied), T1071.001 (clean prior run, no new signal).' },
  ],
  2: [
    { type:'env',    agent:'hyp',  msg:'get_topology() → 8 segments · 10.0.0.0/8 · 2,412 endpoints verified' },
    { type:'env',    agent:'hyp',  msg:'get_asset("WIN-DC01") → Tier-0 DC · crown jewel · 10.0.1.10 confirmed' },
    { type:'env',    agent:'hyp',  msg:'get_account("jsmith") → Corp Workstations · off-hours anomaly · MFA enrolled' },
    { type:'tool',   agent:'hyp',  msg:'search_hunts("T1570") → TH-2026-038 confirmed · 9 hosts · jsmith tool-transfer pivot chain' },
    { type:'relay',  agent:'hyp',  to:'ts',   msg:'T1570 confirmed in prior hunt — do you have a recommended host-hop limit for DC-proximity lateral movement hunts? Checking SK-045.' },
    { type:'relay',  agent:'ts',   to:'hyp',  msg:'yes — SK-045 specifies 2-hop threshold for vCenter-adjacent lateral movement · apply single-hop limit for jsmith pivot chain relative to WIN-DC01',
      detail:'SK-045 was validated against 3 prior hunts. The 2-hop threshold eliminates ~65% of noise from legitimate admin tooling while preserving the attack-chain signal. For a Tier-0 DC as the anchor, we typically tighten to 1-hop for the first analytical pass.' },
    { type:'reason', agent:'hyp',  msg:'🎯 H-01 (T1570): Confirmed · single-hop threshold applied per Tradecraft recommendation · confidence 92%',
      detail:'jsmith contacted 9 hosts across 2 sessions. Single-hop scope: hosts within 1 network hop of WIN-DC01. Confidence elevated 87% → 92% due to Tier-0 involvement and Tradecraft-validated scope reduction.' },
    { type:'tool',   agent:'hyp',  msg:'search_hunts("T1558.003") → TH-2026-035 · 22% FP rate · BackupExec + MSSQLSvc SPNs identified' },
    { type:'relay',  agent:'hyp',  to:'orch', msg:'T1558.003 FP rate 22% in prior run — need CMDB SPN exclusion list before I can scope this properly, otherwise signal is noise-dominated' },
    { type:'relay',  agent:'orch', to:'hyp',  msg:'CMDB SPN exclusion list dispatched — 147 entries · BackupExec (svc-backup$) + all MSSQLSvc/* SPNs included' },
    { type:'reason', agent:'hyp',  msg:'🔔 H-02 (T1558.003): FPs in prior run · 147 SPN exclusions loaded · RC4 threshold tuned to 15/hr · confidence 74%',
      detail:'BackupExec and MSSQLSvc SPNs were generating legitimate RC4 TGS-REQs on schedule. With 147 exclusions applied, the residual signal is attributable to targeted kerberoasting. RC4 threshold adjusted 5 → 15 req/hr to absorb scheduled job noise.' },
    { type:'tool',   agent:'hyp',  msg:'search_hunts("T1071.001") → TH-2025-091 · clean run · zero JA3 fingerprint matches in proxy logs' },
    { type:'reason', agent:'hyp',  msg:'❄️ H-03 (T1071.001): Clean prior run · generating net-new cert-chain hypothesis · confidence 41%',
      detail:'Rather than repeat the zero-yield JA3 hunt, pivoting to C2 frameworks using Let\'s Encrypt certs with <24hr lifetimes. Anomaly path: short-lived cert + non-browser user-agent + high-frequency beacon interval. Novel path — not previously hunted.' },
    { type:'relay',  agent:'hyp',  to:'orch', msg:'hypothesis package ready · H-01(92%) H-02(74%) H-03(41%) · 3 branches resolved · ready for analyst gate',
      detail:'Package summary:\n• H-01 (T1570): conf 92% · 14-host scope · 1-hop limit · jsmith pivot context\n• H-02 (T1558.003): conf 74% · full endpoint scope · 147 SPN exclusions\n• H-03 (T1071.001): conf 41% · net-new cert-chain path · proxy+DNS sources\nHandoff includes: env context, exclusion lists, branch decisions, TTP mappings.' },
    { type:'relay',  agent:'orch', to:'ts',   msg:'hypothesis package received and analyst-approved · begin tradecraft analysis · T1570, T1003.001, T1558.003 in scope' },
    { type:'relay',  agent:'ts',   to:'orch', msg:'acknowledged · skill repository pre-loaded for T1570, T1003.001, T1558.003 · beginning RAA analysis now' },
  ],
  3: [
    { type:'tool',   agent:'ts',   msg:'skills_repo.load_skills(["T1570","T1003.001","T1558.003"]) → SK-045, SK-029, SK-038 matched' },
    { type:'reason', agent:'ts',   msg:'SK-045 (vCenter LM): port 902/903 host-jump pattern active · scoping to vCenter + DC segments',
      detail:'SK-045 identifies lateral movement via VMware vCenter API abuse on ports 902/903. Cross-referencing T1570 transfer timestamps to build a correlated pivot chain.' },
    { type:'reason', agent:'ts',   msg:'SK-029 (LSASS EDR evasion): handle 0x1fffff via NtDuplicateObject · AV/EDR processes pre-excluded',
      detail:'Targets PROCESS_ALL_ACCESS (0x1fffff) handle requests on lsass.exe from unsigned or LOLBin sources. MsMpEng.exe, csagent.sys, SenseIR.exe pre-excluded.' },
    { type:'relay',  agent:'ts',   to:'data', msg:'run EventCode 4769 TGS-REQ · 5-minute buckets · last 7 days · need per-account spike analysis against baseline' },
    { type:'tool',   agent:'data', msg:'querying Splunk ES · EventCode 4769 · 5m bucket · 7-day window · CIM-normalised…' },
    { type:'relay',  agent:'data', to:'ts',   msg:'query complete · 47 process chains scored against 30-day baseline · 3 accounts exceed 3σ spike threshold · raw results attached' },
    { type:'runbook',agent:'ts',   msg:'get_runbook("T1570") → lateral tool transfer · 3 evidence tips loaded · SMB staging + named pipe relay patterns active' },
    { type:'tool',   agent:'ts',   msg:'running process chain analytic · 47 chains cross-referenced against jsmith account activity…' },
    { type:'reason', agent:'ts',   msg:'59 hits on T1570/T1078.002 — CORP\\jsmith pivoted 14 hosts across 2 sessions',
      detail:'Session 1 (23:17–00:43 UTC): 31 events · 8 hosts · SMB share staging via \\ADMIN$\nSession 2 (01:12–01:42 UTC): 28 events · 6 new hosts · named pipe relay (\\pipe\\svcctl)\nWIN-DC01 (Tier-0) and WIN-SQL02 (Tier-1) both touched.' },
    { type:'relay',  agent:'ts',   to:'orch', msg:'⚠ LATERAL MOVEMENT CONFIRMED — CORP\\jsmith pivot chain across 14 hosts including WIN-DC01 (Tier-0) · 59 events · recommend flagging to analyst' },
    { type:'relay',  agent:'orch', to:'ts',   msg:'acknowledged and escalated · continue — run T1003.001 credential access check on WIN-DC01 immediately · this is now the priority branch' },
    { type:'relay',  agent:'ts',   to:'data', msg:'query LSASS access events (Sysmon EventCode 10) on WIN-DC01 only · filter out known AV source images · last 48 hours' },
    { type:'tool',   agent:'data', msg:'querying Sysmon EventCode 10 (ProcessAccess) · WIN-DC01 · non-AV source images · 48h window…' },
    { type:'relay',  agent:'data', to:'ts',   msg:'3 LSASS access events from non-standard processes on WIN-DC01 · all within jsmith session window · results attached' },
    { type:'runbook',agent:'ts',   msg:'get_runbook("T1003.001") → LSASS memory access · critical indicator: handle 0x1fffff · FP: exclude signed AV/EDR images' },
    { type:'warn',   agent:'ts',   msg:'🔴 rundll32.exe opened LSASS with PROCESS_ALL_ACCESS (0x1fffff) on WIN-DC01 at 01:38:22 UTC · risk score 94',
      detail:'rundll32.exe (C:\\Windows\\System32\\rundll32.exe) opened lsass.exe with handle 0x1fffff at 01:38:22 UTC. Process tree: explorer.exe → cmd.exe (PID 4812) → rundll32.exe (PID 7340). No command-line args — consistent with reflective shellcode injection. Matches SK-029 LSASS evasion pattern exactly.' },
    { type:'relay',  agent:'ts',   to:'orch', msg:'🔴 CRITICAL FINDING — LSASS credential dump on Tier-0 DC WIN-DC01 · rundll32 PROCESS_ALL_ACCESS · score 94 · recommend immediate analyst escalation' },
    { type:'relay',  agent:'orch', to:'rv',   msg:'urgent — check deployed Splunk rules: is rundll32→LSASS with handle 0x1fffff on WIN-DC01 currently covered by any active detection?' },
    { type:'tool',   agent:'rv',   msg:'scanning 847 deployed Splunk ES rules for LSASS + rundll32 + PROCESS_ALL_ACCESS coverage…' },
    { type:'relay',  agent:'rv',   to:'orch', msg:'checked all 847 rules — no deployed rule covers rundll32→LSASS with PROCESS_ALL_ACCESS · detection gap confirmed · WIN-DC01 is currently blind to this technique' },
    { type:'relay',  agent:'orch', to:'dl',   msg:'critical gap confirmed by Validation · T1003.001 LSASS on WIN-DC01 is priority-1 rule for Detection Logic · escalating ahead of T1053.005 and T1547.001' },
    { type:'done',   agent:'ts',   msg:'tradecraft complete · T1570 + T1003.001 confirmed findings · gaps T1053.005, T1547.001, T1558.003 forwarded',
      detail:'RAA summary:\n• T1570: 59 confirmed hits · jsmith 14-host pivot chain · PASS TO KEEP\n• T1003.001: 1 critical hit · rundll32 LSASS 0x1fffff on WIN-DC01 · PASS TO KEEP\n• T1558.003: 0 hits above tuned threshold after SPN exclusion\nDetection Logic gaps: T1053.005 (no rule), T1547.001 (no rule), T1558.003 (needs refinement).' },
  ],
  4: [
    { type:'relay',  agent:'dl',   to:'ts',   msg:'received gap list · before I draft the T1003.001 rule — confirm exact FP exclusions: which process images should I whitelist for LSASS access?' },
    { type:'relay',  agent:'ts',   to:'dl',   msg:'exclude: MsMpEng.exe, csagent.sys, SenseIR.exe, CrowdStrike sensor PID · trigger only on PROCESS_ALL_ACCESS (0x1fffff) from unsigned or LOLBin source · signed MS binaries in EXCL list',
      detail:'SK-029 exclusion list validated against 6 months of endpoint telemetry. These 4 exclusions reduce FP rate from 34% to under 2% while preserving all known LSASS evasion patterns.' },
    { type:'runbook',agent:'dl',   msg:'get_runbook("T1053.005") → 2 SPL templates loaded · SCCM ConfigMgr_* exclusion pattern retrieved from TH-2025-091' },
    { type:'tool',   agent:'dl',   msg:'generating SPL rule for T1053.005 — schtasks.exe /create pattern with SCCM exclusion…' },
    { type:'relay',  agent:'dl',   to:'rv',   msg:'please validate DL-2026-041-001 (T1053.005-schtasks-create) · SCCM exclusion applied · targeting est. FP < 2%' },
    { type:'tool',   agent:'rv',   msg:'validating DL-2026-041-001 · schema check · CIM field mapping · FP rate simulation against 30-day baseline…' },
    { type:'relay',  agent:'rv',   to:'dl',   msg:'DL-2026-041-001 PASS · schema OK · FP rate 1.8% confirmed · SCCM exclusion verified · cleared for deployment' },
    { type:'tool',   agent:'dl',   msg:'generating SPL rule for T1547.001 — Registry Run Key persistence · monitoring HKCU/HKLM Run keys…' },
    { type:'relay',  agent:'dl',   to:'rv',   msg:'please validate DL-2026-041-002 (T1547.001-run-key-persist)' },
    { type:'tool',   agent:'rv',   msg:'validating DL-2026-041-002 · schema check · CIM field mapping…' },
    { type:'relay',  agent:'rv',   to:'dl',   msg:'DL-2026-041-002 WARN — registry_value_data field is not CIM-mapped in the Endpoint data model · rule logic is sound but field will be null in normalised searches',
      detail:'The field "registry_value_data" is not part of the Splunk CIM Endpoint model. Recommend adding a field alias in transforms.conf: registry_value_data → registry_value_text. Rule is functionally correct but will miss events in CIM-compliant dashboards until aliased.' },
    { type:'relay',  agent:'dl',   to:'orch', msg:'DL-2026-041-002 has a CIM field mapping issue flagged by Validation · registry_value_data unmapped · how should I proceed — hold for fix or deploy with WARN?' },
    { type:'relay',  agent:'orch', to:'dl',   msg:'deploy with WARN · flag for post-hunt CIM remediation · add to analyst review checklist · do not block the hunt on this' },
    { type:'tool',   agent:'dl',   msg:'tuning T1558.003 Kerberoasting rule · applying 147-entry BackupExec + MSSQLSvc SPN exclusion list…' },
    { type:'relay',  agent:'dl',   to:'rv',   msg:'please validate DL-2026-041-003 (T1558.003-kerberoasting) · SPN exclusion from Hypothesis package applied · targeting FP < 1%' },
    { type:'tool',   agent:'rv',   msg:'validating DL-2026-041-003 · BackupExec + MSSQLSvc exclusion list integrity check · FP rate simulation…' },
    { type:'relay',  agent:'rv',   to:'dl',   msg:'DL-2026-041-003 PASS · schema OK · FP rate 0.4% · all 147 SPN exclusions verified · cleared for deployment' },
    { type:'relay',  agent:'dl',   to:'orch', msg:'all 3 rules validated · DL-2026-041-001 PASS · DL-2026-041-002 WARN (CIM) · DL-2026-041-003 PASS · pushing to Splunk ES deployment queue now' },
    { type:'relay',  agent:'orch', to:'dl',   msg:'confirmed · excellent work · package logged to Keep stage · CIM issue flagged for analyst · hunt TH-2026-041 entering evidence consolidation' },
    { type:'done',   agent:'dl',   msg:'3 rules deployed to Splunk ES queue · 2 PASS · 1 WARN · hunt TH-2026-041 detection coverage active',
      detail:'Deployment summary:\n• DL-2026-041-001 (T1053.005): PASS · FP 1.8% · severity HIGH\n• DL-2026-041-002 (T1547.001): WARN · registry_value_data CIM mapping pending · severity MEDIUM\n• DL-2026-041-003 (T1558.003): PASS · FP 0.4% · BackupExec exclusion verified · severity HIGH\nAll queued in Splunk ES deployment pipeline. Analyst sign-off required on WARN item before production promotion.' },
  ],
};

const feedStepLabels = ['Select Intel','TTP Extraction','Hypotheses','Tradecraft','Detection Logic'];
let feedTimers = [];

function feedAddSep(label) {
  feedAddBlockSep(label);
}

function feedAddEntry(e) {
  const { type, agent, to } = e;
  feedAddBlock(e);
  _setAgentLegendStatus(agent, type === 'done' ? 'idle' : 'active');
  if (to) _setAgentLegendStatus(to, 'active');
  pulseTopoNode(agent);
  if (to) {
    setTimeout(() => pulseTopoNode(to), 180);
    pulseTopoLine(agent === 'orch' ? to : agent);
  } else {
    pulseTopoLine(agent);
  }
}

// ── Big agents reasoning feed ──
let activeFeedFilter = 'all';
let _stepStartTime   = 0;

function feedAddBlock(e) {
  const { type, agent, msg, detail, to } = e;
  const feed = document.getElementById('agents-reasoning-feed');
  if (!feed) return;
  const empty = document.getElementById('agents-feed-empty');
  if (empty) empty.remove();
  const ag    = feedAgents[agent] || { icon:'🤖', name:'Agent' };
  const col   = feedAgentColors[agent] || { bg:'rgba(148,163,184,.15)', border:'#94a3b8' };
  const now   = new Date();
  const ts    = `${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;
  const elapsed = _stepStartTime ? ` +${((Date.now() - _stepStartTime) / 1000).toFixed(1)}s` : '';
  const badge = feedBadgeLabels[type] || type.toUpperCase();
  const detailHtml = detail
    ? `<button class="feed-block-toggle" onclick="toggleFeedDetail(this)">▼ details</button><div class="feed-block-detail" style="display:none;">${detail.replace(/\n/g,'<br>')}</div>`
    : '';

  let headHtml;
  if (type === 'relay' && to) {
    const toAg  = feedAgents[to] || { icon:'🤖', name:'Agent' };
    const toCol = feedAgentColors[to] || { bg:'rgba(148,163,184,.15)', border:'#94a3b8' };
    headHtml = `
      <div class="feed-block-avatar" style="background:${col.bg};border:1px solid ${col.border};">${ag.icon}</div>
      <span class="feed-block-name">${ag.name}</span>
      <span class="feed-relay-arrow">→</span>
      <div class="feed-block-avatar" style="background:${toCol.bg};border:1px solid ${toCol.border};">${toAg.icon}</div>
      <span class="feed-block-name feed-block-name-to">${toAg.name}</span>
      <span class="feed-block-badge fb-relay">${badge}</span>
      <span class="feed-block-ts">${ts}<span class="feed-block-elapsed">${elapsed}</span></span>`;
  } else {
    headHtml = `
      <div class="feed-block-avatar" style="background:${col.bg};border:1px solid ${col.border};">${ag.icon}</div>
      <span class="feed-block-name">${ag.name}</span>
      <span class="feed-block-badge fb-${type}">${badge}</span>
      <span class="feed-block-ts">${ts}<span class="feed-block-elapsed">${elapsed}</span></span>`;
  }

  const el = document.createElement('div');
  el.className = type === 'relay' ? 'feed-block feed-block-relay' : 'feed-block';
  el.dataset.agent = agent;
  el.dataset.to    = to || '';
  // apply current filter
  if (activeFeedFilter !== 'all' && el.dataset.agent !== activeFeedFilter && el.dataset.to !== activeFeedFilter) {
    el.style.display = 'none';
  }
  el.innerHTML = `<div class="feed-block-head">${headHtml}</div><div class="feed-block-msg">${msg}</div>${detailHtml}`;
  feed.appendChild(el);
  feed.scrollTop = feed.scrollHeight;
}

function setFeedFilter(agent, btn) {
  activeFeedFilter = agent;
  document.querySelectorAll('.ffp').forEach(b => b.classList.remove('ffp-on'));
  if (btn) btn.classList.add('ffp-on');
  const feed = document.getElementById('agents-reasoning-feed');
  if (!feed) return;
  feed.querySelectorAll('.feed-block, .feed-block-relay').forEach(block => {
    if (agent === 'all') {
      block.style.display = '';
    } else {
      block.style.display = (block.dataset.agent === agent || block.dataset.to === agent) ? '' : 'none';
    }
  });
  // always show separators when filtering (context anchors)
  feed.querySelectorAll('.feed-block-sep').forEach(sep => { sep.style.display = ''; });
}

function feedAddBlockSep(label) {
  const feed = document.getElementById('agents-reasoning-feed');
  if (!feed) return;
  const el = document.createElement('div');
  el.className = 'feed-block-sep';
  el.innerHTML = `<div class="feed-block-sep-line"></div><span class="feed-block-sep-label">${label}</span><div class="feed-block-sep-line"></div>`;
  feed.appendChild(el);
  feed.scrollTop = feed.scrollHeight;
}

function clearAgentsFeed() {
  const feed = document.getElementById('agents-reasoning-feed');
  if (!feed) return;
  feed.innerHTML = `<div class="agents-feed-empty" id="agents-feed-empty">
    <div style="font-size:32px;margin-bottom:12px;opacity:.25;">🤖</div>
    <div style="font-size:13px;font-weight:600;color:var(--sub);margin-bottom:7px;">No reasoning activity yet</div>
    <div style="font-size:11px;color:var(--muted);max-width:280px;line-height:1.6;">Step through the LOCK pipeline tabs to watch agents reason, collaborate, and make decisions in real time.</div>
  </div>`;
  const dot = document.getElementById('agents-feed-dot');
  const statusEl = document.getElementById('agents-feed-status');
  if (dot) dot.style.opacity = '0.3';
  if (statusEl) statusEl.textContent = 'Waiting for pipeline…';
  // Reset legend
  ['orch','hyp','data','ts','dl'].forEach(a => _setAgentLegendStatus(a, 'idle'));
  // Reset pipeline steps
  for (let i = 0; i < 5; i++) _setAgentProgStep(i, 'pending');
  // Reset filter to All
  _stepStartTime = 0;
  activeFeedFilter = 'all';
  setFeedFilter('all', document.querySelector('.ffp'));
}

function _setAgentLegendStatus(agent, status) {
  const el = document.getElementById('aleg-' + agent + '-s');
  if (!el) return;
  el.textContent = status;
  el.style.color = status === 'active' ? 'var(--green)' : status === 'done' ? 'var(--blue)' : 'var(--muted)';
}

function _setAgentProgStep(step, state) {
  const el = document.getElementById('aprog-' + step);
  if (!el) return;
  const dot = el.querySelector('.aprog-dot');
  if (state === 'active') { el.style.color = 'var(--blue)'; if (dot) dot.textContent = '●'; }
  else if (state === 'done') { el.style.color = 'var(--green)'; if (dot) dot.textContent = '✓'; }
  else { el.style.color = 'var(--muted)'; if (dot) dot.textContent = '○'; }
}

function toggleFeedDetail(btn) {
  const detail = btn.nextElementSibling;
  const isOpen = detail.style.display !== 'none';
  detail.style.display = isOpen ? 'none' : '';
  btn.textContent = isOpen ? '▼ details' : '▲ hide';
}

// ── Topology node / line pulse ──
const _topoLineMap = {
  'hyp':'topo-l-hyp','data':'topo-l-data','ts':'topo-l-ts','dl':'topo-l-dl'
};
function pulseTopoNode(agent) {
  const el = document.getElementById('topo-c-' + agent);
  if (!el) return;
  el.classList.remove('topo-node-lit');
  void el.getBoundingClientRect();
  el.classList.add('topo-node-lit');
  setTimeout(() => el.classList.remove('topo-node-lit'), 1400);
}
function pulseTopoLine(agent) {
  // pulse the line between orch and this agent (lines radiate from orch)
  const lineId = _topoLineMap[agent];
  if (!lineId) return;
  const el = document.getElementById(lineId);
  if (!el) return;
  el.classList.remove('topo-line-lit');
  void el.getBoundingClientRect();
  el.classList.add('topo-line-lit');
  setTimeout(() => el.classList.remove('topo-line-lit'), 1000);
}

function playFeedStep(step) {
  feedTimers.forEach(clearTimeout);
  feedTimers = [];
  _stepStartTime = Date.now();
  const entries = feedSteps[step] || [];

  // Drive agents-feed header
  const dot      = document.getElementById('agents-feed-dot');
  const agStatus = document.getElementById('agents-feed-status');
  if (dot) dot.style.opacity = '1';
  if (agStatus) agStatus.textContent = 'streaming — ' + (feedStepLabels[step] || 'Step ' + step);
  _setAgentProgStep(step, 'active');

  feedAddSep(feedStepLabels[step] || 'Step ' + step);
  let delay = 0;
  entries.forEach(e => {
    delay += 500 + Math.random() * 400;
    feedTimers.push(setTimeout(() => feedAddEntry(e), delay));
  });
  // mark idle after last entry
  feedTimers.push(setTimeout(() => {
    if (dot) dot.style.opacity = '0.4';
    if (agStatus) agStatus.textContent = 'idle · last: ' + (feedStepLabels[step] || 'Step ' + step);
    _setAgentProgStep(step, 'done');
    // Reset active agent statuses to idle
    ['orch','hyp','data','ts','dl'].forEach(a => _setAgentLegendStatus(a, 'idle'));
  }, delay + 600));
}

function setStep(i) {
  const isForward = i > maxStep;
  maxStep = Math.max(maxStep, i);
  for (let j = 0; j < 5; j++) {
    const n = document.getElementById('ps' + j);
    if (n) n.className = 'ps-node ' + (j === i ? 'curr' : j < i || j < maxStep ? 'done' : 'wait');
    if (j < 4) {
      const l = document.getElementById('pl' + j);
      if (l) l.className = 'ps-line' + (j < i || j < maxStep ? ' done' : '');
    }
    const s = document.getElementById('stage-' + j);
    if (s) s.className = 'stage card' + (j <= i ? ' show' : '');
  }
  updateAgentPills(maxStep);
  const stageLabels = ['Learn · Select Intel', 'Learn · TTP Extraction', 'Learn · Hypotheses', 'Learn · Tradecraft', 'Learn · Detection'];
  const stageEl = document.getElementById('lhc-stage');
  if (stageEl) stageEl.textContent = stageLabels[i] || stageLabels[0];
  if (maxStep >= 2) {
    const hypEl = document.getElementById('lhc-hyp');
    if (hypEl) { hypEl.textContent = '3 generated'; hypEl.style.color = ''; }
    const pastCard = document.getElementById('learn-past-card');
    if (pastCard) pastCard.style.display = '';
  }
  if (isForward) playFeedStep(i);
  // Scroll to the target stage (auto-expand if collapsed)
  const stageTarget = document.getElementById('stage-' + i);
  if (stageTarget) {
    stageTarget.classList.remove('collapsed');
    setTimeout(() => stageTarget.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50);
  }
}
