/* ── Pipeline / Feed ────────────────────────────────────────────────────
   LOCK pipeline state (maxStep, feedSteps, feedAgents), feed renderer
   (feedAddEntry/Block/Sep), agent pills, topology pulse, setStep/play.
   Loaded after app.js — references globals declared there.
   ──────────────────────────────────────────────────────────────────────── */
// ── Pipeline steps ──
let maxStep = -1;
let pipelineLocked = false; // true for closed/archived hunts — setStep is a no-op

// Snapshots of Stage 0 / Stage 1 original content — captured at first load
let _origTtpTbody      = null;
let _origStage0InfoBar = '';
let _origStage1InfoBar = '';

function updateAgentPills(i) {
  const pills = [
    // step 0: report selected, pipeline starting
    { hyp:['Running','chip-blue',30,'Analysing CTI · 8 TTPs queued'],               orch:['Running','chip-blue',50,'Routing tasks · pipeline initialised'],  data:['Running','chip-blue',50,'Connecting to Splunk ES…'],              ts:['Waiting','chip-gray',0,'Awaiting TTPs'],               dl:['Waiting','chip-gray',0,'Awaiting tradecraft notes'] },
    // step 1: TTPs loaded from upstream pipeline, hypothesis agent working
    { hyp:['Running','chip-blue',70,'Cross-referencing past hunts · 3 recalled'],     orch:['Running','chip-blue',70,'Routing tasks · 2 agents active'],        data:['Done','chip-green',100,'Splunk data ready · indices available'], ts:['Waiting','chip-gray',0,'Awaiting hypotheses'],          dl:['Waiting','chip-gray',0,'Awaiting tradecraft notes'] },
    // step 2: hypotheses generated by Hypothesis Agent
    { hyp:['Done','chip-green',100,'4 hypotheses generated · handed to Orchestrator'],orch:['Done','chip-green',100,'Hypotheses routed · pipeline continues'],   data:['Done','chip-green',100,'Splunk data available · CIM-normalised'], ts:['Review','chip-blue',80,'4 hypotheses ready for review'], dl:['Waiting','chip-gray',0,'Awaiting tradecraft notes'] },
    // step 3: tradecraft running
    { hyp:['Done','chip-green',100,'4 hypotheses generated · analyst notes applied'], orch:['Done','chip-green',100,'Hunt coordinated · all tasks routed'],     data:['Done','chip-green',100,'Splunk data available · CIM-normalised'], ts:['Active','chip-blue',100,'Querying Splunk ES · 59 hits'],  dl:['Running','chip-blue',40,'Awaiting tradecraft notes'] },
    // step 4: detection logic + rule validation (via tool)
    { hyp:['Done','chip-green',100,'4 hypotheses generated · analyst notes applied'], orch:['Done','chip-green',100,'Hunt coordinated · all tasks routed'],     data:['Done','chip-green',100,'Splunk data available · CIM-normalised'], ts:['Done','chip-green',100,'Tradecraft analysis complete'],  dl:['Active','chip-blue',90,'Generating rules · validating via RuleVal tool…'] },
  ];
  const s = pills[Math.min(i, pills.length - 1)];
  function set(id, [chip, cls, pct, status]) {
    const el = document.getElementById(id);
    if (!el) return;
    el.style.opacity = '1';
    document.getElementById(id + '-status').textContent = status;
    document.getElementById(id + '-fill').style.width = pct + '%';
    const c = document.getElementById(id + '-chip');
    c.textContent = chip; c.className = 'chip ' + cls; c.style.fontSize = '10px';
  }
  set('ap-orch', s.orch);
  set('ap-hyp',  s.hyp);  set('ap-data', s.data);
  set('ap-ts',   s.ts);   set('ap-dl',   s.dl);
}

// ── Live agent feed ──
const feedAgents = {
  hyp:  { icon:'💡', name:'Hypothesis' },
  orch: { icon:'🎛️', name:'Orchestrator' },
  data: { icon:'🗄️', name:'Data Eng' },
  ts:   { icon:'🧠', name:'Tradecraft' },
  dl:   { icon:'⚙️',  name:'Detection Logic' },
  rv:   { icon:'✅', name:'Rule Validation' },
};
const feedPfx = { tool:'→', reason:'↳', done:'✓', warn:'⚠', runbook:'📖', env:'🏗️', rv:'✅', relay:'↗' };
const feedAgentColors = {
  orch: { bg:'rgba(59,130,246,.18)',  border:'#3b82f6' },
  hyp:  { bg:'rgba(20,184,166,.18)', border:'#14b8a6' },
  data: { bg:'rgba(99,102,241,.18)', border:'#6366f1' },
  ts:   { bg:'rgba(245,158,11,.18)', border:'#f59e0b' },
  dl:   { bg:'rgba(16,185,129,.18)', border:'#10b981' },
  rv:   { bg:'rgba(168,85,247,.18)', border:'#a855f7' },
};
const feedBadgeLabels = { tool:'TOOL CALL', reason:'REASONING', done:'COMPLETE', warn:'WARNING', runbook:'RUNBOOK', env:'ENV CTX', rv:'RULE VALID', relay:'MSG' };

const feedSteps = {
  0: [
    { type:'reason', agent:'orch', msg:'CISA AA24-038A (Volt Typhoon) · scoring 8 TTPs by advisory prevalence × asset exposure × prior hunt recall · Tier-0 DC (WIN-DC01) in scope elevates credential-access and lateral-movement branches',
      detail:'Scoring factors applied per TTP:\n• Advisory signal strength: frequency and specificity in CISA advisory text\n• Asset exposure: whether in-scope assets match technique target (e.g. WIN-DC01 for credential access)\n• Prior hunt recall: confirmed hits or clean runs in TH-2026-035/038/091\nT1078.002 (Valid Accounts, conf 95%) scored highest but is already covered by an active rule — merged as supporting signal into T1570 lateral movement scope rather than a standalone hypothesis.' },
    { type:'relay',  agent:'data', to:'orch', msg:'connected · 4 indices confirmed · sysmon(7d) windows(30d) network(14d) security(90d) · CIM normalisation verified',
      detail:'Auth via service account token. All 4 indices ingested and CIM-normalised. Baseline window set to 30 days. Ready for query workload.' },
    { type:'relay',  agent:'orch', to:'hyp',  get msg() {
        const r = (typeof repoData !== 'undefined' && typeof activeReportId !== 'undefined')
          ? repoData.find(x => x.id === activeReportId) : null;
        const count = r ? r.ttps : 8;
        const title = r ? r.title : 'CISA AA24-038A — Volt Typhoon';
        return `stand by — loading ${count} TTPs from ${title} upstream pipeline · pre-load environment topology to scope hypotheses`;
      } },
    { type:'env',    agent:'orch', msg:'get_topology() → 8 network segments · 10.0.0.0/8 scope · 2,412 endpoints · Tier-0 isolation active' },
    { type:'done',   agent:'orch', msg:'8 TTPs loaded · confidence scored · T1570(87%) T1003.001(82%) T1558.003(74%) T1071.001(78%) · 4 hypotheses flagged · routing to Stage 1',
      detail:'Advisory signal strength scored across 8 TTPs. 4 hypotheses selected for this hunt:\n• T1570 — Lateral Tool Transfer (conf 87%)\n• T1003.001 — LSASS Credential Dumping (conf 82%)\n• T1558.003 — Kerberoasting (conf 74%)\n• T1071.001 — C2 Beacon via HTTPS (conf 78%)\nT1078.002 (Valid Accounts, conf 95%) acts as supporting authentication anomaly signal — scoped into T1570 hypothesis, not a separate hunt target.' },
  ],
  1: [
    { type:'tool',   agent:'hyp',  msg:'search_hunts("T1078.002") → 3 past hunts retrieved · TH-2026-038 overlaps on jsmith credential abuse' },
    { type:'tool',   agent:'hyp',  msg:'get_hunt("TH-2026-038") → lateral movement confirmed · CORP\\jsmith pivoted 9 hosts · analyst notes loaded' },
    { type:'tool',   agent:'hyp',  msg:'check_coverage("T1078.002") → 1 existing rule active · last triggered 4 days ago · possible detection gap' },
    { type:'relay',  agent:'hyp',  to:'orch', msg:'T1078.002 — prior confirmed hits in TH-2026-038 · existing rule stale (4 days) · need Tier-0 asset context before finalising scope' },
    { type:'env',    agent:'orch', msg:'get_asset("WIN-DC01") → Tier-0 Domain Controller · 10.0.1.10 · DC VLAN · CrowdStrike Falcon 7.1' },
    { type:'env',    agent:'orch', msg:'get_account("jsmith") → Corp Workstations segment · off-hours logon anomaly flagged · MFA enrolled' },
    { type:'reason', agent:'hyp',  msg:'confidence on T1078.002 raised to 95% — off-hours logon + Tier-0 DC exposure confirmed',
      detail:'Prior hunt TH-2026-038 confirmed lateral movement via CORP\\jsmith credential abuse. Off-hours logon from 23:17–01:42 UTC maps directly to the current attack window. Existing coverage rule last hit 4 days ago — suggests actor may have shifted technique. Elevating confidence 87% → 95% and narrowing scope to DC VLAN (10.0.1.0/24).' },
    { type:'relay',  agent:'hyp',  to:'data', msg:'run EventCode 4769 TGS-REQ baseline · last 30 days · 5-minute buckets · flag DC VLAN segment' },
    { type:'tool',   agent:'data', msg:'querying Splunk ES · EventCode 4769 · 30-day window · CIM normalisation applied…',
      spl:'index=wineventlog EventCode=4769 | bucket _time span=5m | stats count by _time, src_user, dest | where count > 15',
      results:{ cols:['_time','src_user','dest','count'], rows:[
        ['2026-05-22 23:20','CORP\\jsmith','WIN-DC01','47'],
        ['2026-05-22 23:15','CORP\\jsmith','WIN-SQL02','23'],
        ['2026-05-22 01:12','CORP\\jsmith','WIN-DC01','31'],
        ['2026-05-21 14:30','CORP\\admin.t','WIN-DC01','8'],
        ['2026-05-21 08:15','CORP\\svc-backup','WIN-FS01','3'],
      ]}
    },
    { type:'relay',  agent:'data', to:'hyp',  msg:'baseline complete · 2.4M events in scope · mean 18,400 ev/hr · DC VLAN (10.0.1.0/24) flagged Tier-0 · 3σ spike threshold set',
      detail:'2,412,087 Kerberos TGS-REQ events over 30 days. Fields mapped: src_user, dest, ticket_encryption_type. Spike threshold = 3σ above per-account daily average. DC VLAN ACL anomaly: 3 workstation IPs accessed DC segment outside maintenance window.' },
    { type:'reason', agent:'orch', msg:'scope locked: 4 hypotheses · Lateral Tool Transfer · LSASS Credential Dumping · Kerberoasting · C2 Beacon via HTTPS · awaiting analyst gate approval',
      detail:'Decision matrix:\n• T1570 (Lateral Tool Transfer) — conf 87% → INCLUDE · confirmed TH-2026-038 (9-host jsmith pivot), Tier-0 DC reached\n• T1003.001 (LSASS Credential Dumping) — conf 82% → INCLUDE · follows lateral movement to WIN-DC01, SK-029 exclusion list pre-loaded\n• T1558.003 (Kerberoasting) — conf 74% → INCLUDE · 147 CMDB SPN exclusions loaded, RC4 threshold tuned to >3 SPNs/user/5m, FP rate drops from 22% → <2%\n• T1071.001 (C2 Beacon via HTTPS) — conf 78% → INCLUDE · net-new cert-chain path not previously hunted, JA3 fingerprint detection available\nT1078.002 (Valid Accounts) — conf 95%, off-hours anomaly → SUPPORTING SIGNAL · merged into T1570 scope (jsmith credential context), not a separate hypothesis' },
  ],
  2: [
    { type:'tool',   agent:'hyp',  msg:'search_hunts("T1570") → TH-2026-038 confirmed · 9 hosts · jsmith tool-transfer pivot chain' },
    { type:'relay',  agent:'hyp',  to:'ts',   msg:'T1570 confirmed in prior hunt — do you have a recommended host-hop limit for DC-proximity lateral movement hunts? Checking SK-045.' },
    { type:'relay',  agent:'ts',   to:'hyp',  msg:'yes — SK-045 specifies 2-hop threshold for vCenter-adjacent lateral movement · apply single-hop limit for jsmith pivot chain relative to WIN-DC01',
      detail:'SK-045 was validated against 3 prior hunts. The 2-hop threshold eliminates ~65% of noise from legitimate admin tooling while preserving the attack-chain signal. For a Tier-0 DC as the anchor, we typically tighten to 1-hop for the first analytical pass.' },
    { type:'reason', agent:'hyp',  msg:'🎯 H-01 · Lateral Tool Transfer (T1570): confidence 92% · single-hop threshold applied · jsmith pivot chain confirmed',
      detail:'jsmith contacted 9 hosts across 2 sessions (TH-2026-038). Single-hop scope: hosts within 1 network hop of WIN-DC01 per SK-045 recommendation. Confidence elevated 87% → 92% due to Tier-0 involvement. T1078.002 (off-hours auth anomaly) scoped in as supporting signal for this hypothesis.' },
    { type:'tool',   agent:'hyp',  msg:'search_hunts("T1003.001") → TH-2026-038 overlaps · LSASS access found post-lateral-movement · SK-029 pattern available' },
    { type:'reason', agent:'hyp',  msg:'🔴 H-02 · LSASS Credential Dumping (T1003.001): confidence 82% · SK-029 exclusion list pre-loaded · follows T1570 chain to WIN-DC01',
      detail:'Lateral movement to Tier-0 DC (WIN-DC01) makes credential dumping highly likely as the next step. SK-029 identifies PROCESS_ALL_ACCESS (0x1fffff) handle requests on lsass.exe from non-security-tool processes. Scope: Sysmon EventCode=10 on DC VLAN.' },
    { type:'tool',   agent:'hyp',  msg:'search_hunts("T1558.003") → TH-2026-035 · 22% FP rate · BackupExec + MSSQLSvc SPNs identified' },
    { type:'relay',  agent:'hyp',  to:'orch', msg:'T1558.003 FP rate 22% in prior run — need CMDB SPN exclusion list before I can scope this properly, otherwise signal is noise-dominated' },
    { type:'relay',  agent:'orch', to:'hyp',  msg:'CMDB SPN exclusion list dispatched — 147 entries · BackupExec (svc-backup$) + all MSSQLSvc/* SPNs included' },
    { type:'reason', agent:'hyp',  msg:'🔔 H-03 · Kerberoasting (T1558.003): confidence 74% · 147 SPN exclusions loaded · RC4 threshold tuned to >3 SPNs/user/5m · FP rate <2%',
      detail:'BackupExec and MSSQLSvc SPNs were generating legitimate RC4 TGS-REQs on schedule. With 147 exclusions applied, the residual signal is attributable to targeted kerberoasting. SPN-diversity threshold raised from >1 to >3 unique SPNs per user per 5-minute window to absorb scheduled job noise.' },
    { type:'tool',   agent:'hyp',  msg:'search_hunts("T1071.001") → TH-2025-091 · clean run · zero JA3 fingerprint matches in proxy logs' },
    { type:'reason', agent:'hyp',  msg:'❄️ H-04 · C2 Beacon via HTTPS (T1071.001): confidence 78% · net-new cert-chain path · JA3 fingerprint detection available',
      detail:'Prior run (TH-2025-091) found zero JA3 hits — pivoting to a different detection path: short-lived Let\'s Encrypt certs (<24hr lifetime) + non-browser user-agent + regular beacon interval. This path was not previously hunted and covers Cobalt Strike malleable C2 profiles.' },
    { type:'relay',  agent:'hyp',  to:'orch', msg:'hypothesis package ready · 4 branches resolved · ready for analyst gate',
      detail:'Package summary:\n• H-01 · Lateral Tool Transfer (T1570): conf 92% · 14-host scope · 1-hop limit · jsmith pivot context\n• H-02 · LSASS Credential Dumping (T1003.001): conf 82% · DC VLAN scope · SK-029 exclusion list pre-loaded\n• H-03 · Kerberoasting (T1558.003): conf 74% · full endpoint scope · 147 SPN exclusions\n• H-04 · C2 Beacon via HTTPS (T1071.001): conf 78% · net-new cert-chain path · proxy+DNS sources\nHandoff includes: env context, exclusion lists, branch decisions, TTP mappings.' },
  ],
  3: [
    { type:'tool',   agent:'ts',   msg:'skills_repo.load_skills(["T1570","T1003.001","T1558.003","T1071.001"]) → SK-045, SK-029, SK-038, SK-071 matched' },
    { type:'reason', agent:'ts',   msg:'SK-045 (vCenter LM): port 902/903 host-jump pattern active · scoping to vCenter + DC segments',
      detail:'SK-045 identifies lateral movement via VMware vCenter API abuse on ports 902/903. Cross-referencing T1570 transfer timestamps to build a correlated pivot chain.' },
    { type:'reason', agent:'ts',   msg:'SK-029 (LSASS EDR evasion): handle 0x1fffff via NtDuplicateObject · AV/EDR processes pre-excluded',
      detail:'Targets PROCESS_ALL_ACCESS (0x1fffff) handle requests on lsass.exe from unsigned or LOLBin sources. MsMpEng.exe, csagent.sys, SenseIR.exe pre-excluded.' },
    { type:'relay',  agent:'ts',   to:'data', msg:'run EventCode 4769 TGS-REQ · 5-minute buckets · last 7 days · need per-account spike analysis against baseline' },
    { type:'tool',   agent:'data', msg:'querying Splunk ES · EventCode 4769 · 5m bucket · 7-day window · CIM-normalised…',
      spl:'index=wineventlog EventCode=4769 earliest=-7d | bucket _time span=5m | stats count by _time, src_user, dest, ticket_encryption_type | where count > 5',
      results:{ cols:['_time','src_user','dest','count'], rows:[
        ['2026-05-22 23:20','CORP\\jsmith','WIN-DC01','47'],
        ['2026-05-22 23:17','CORP\\jsmith','WIN-SQL02','29'],
        ['2026-05-22 01:14','CORP\\jsmith','WIN-FS01','18'],
      ]}
    },
    { type:'relay',  agent:'data', to:'ts',   msg:'query complete · 47 TGS-REQ spikes scored against 30-day per-account baseline · 3 src_users exceed 3σ threshold · results attached' },
    { type:'reason', agent:'ts',   msg:'only CORP\\jsmith is anomalous — admin.t (8 req) and svc-backup (3 req) are within expected range for scheduled tasks · sole focus: jsmith spike clusters at 23:17 and 01:12 UTC' },
    { type:'reason', agent:'ts',   msg:'SK-045 criteria applied to T1570 hunt scope: ADMIN$ file drop (EventCode 5145) paired within 60s of service install (EventCode 7045); named pipe relay (\\\\pipe\\\\svcctl) as high-fidelity secondary indicator',
      detail:'SK-045 evidence framework:\n• Primary: EventCode 5145 (share=ADMIN$) → EventCode 7045 (service install) on same dest host within 60s window\n• Secondary: named pipe access \\pipe\\svcctl correlating with the same session timeframe\n• Scope threshold: 1-hop from WIN-DC01 (tightened from SK-045 default of 2-hop for a Tier-0 anchor)\nAll 3 patterns present in jsmith sessions — confirms technique match.' },
    { type:'reason', agent:'ts',   msg:'59 hits on T1570 — CORP\\jsmith pivoted 14 hosts across 2 sessions',
      detail:'Session 1 (23:17–00:43 UTC): 31 events · 8 hosts · SMB share staging via \\ADMIN$\nSession 2 (01:12–01:42 UTC): 28 events · 6 new hosts · named pipe relay (\\pipe\\svcctl)\nWIN-DC01 (Tier-0) and WIN-SQL02 (Tier-1) both touched.' },
    { type:'relay',  agent:'ts',   to:'orch', msg:'⚠ LATERAL MOVEMENT CONFIRMED — CORP\\jsmith pivot chain across 14 hosts including WIN-DC01 (Tier-0) · 59 events · recommend flagging to analyst' },
    { type:'relay',  agent:'orch', to:'ts',   msg:'acknowledged and escalated · continue — run T1003.001 credential access check on WIN-DC01 immediately · this is now the priority branch' },
    { type:'warn',   agent:'data', msg:'Splunk ES query timeout · peak load on sysmon index · retrying with optimised field filter…' },
    { type:'tool',   agent:'data', msg:'querying Sysmon EventCode 10 (ProcessAccess) · WIN-DC01 · non-AV source images · 48h window…',
      spl:'index=sysmon EventCode=10 TargetImage="*lsass.exe" host="WIN-DC01" earliest=-48h | where NOT match(SourceImage,"(?i)(MsMpEng|csagent|SenseIR|CrowdStrike)") | table _time, SourceImage, TargetImage, GrantedAccess, SourceProcessId',
      results:{ cols:['_time','SourceImage','GrantedAccess','SourceProcessId'], rows:[
        ['2026-05-23 01:38:22','C:\\Windows\\System32\\rundll32.exe','0x1fffff','7340'],
        ['2026-05-23 01:31:05','C:\\Windows\\System32\\rundll32.exe','0x1410','7201'],
        ['2026-05-23 01:22:44','C:\\Windows\\System32\\cmd.exe','0x1410','4812'],
      ]}
    },
    { type:'relay',  agent:'data', to:'ts',   msg:'3 LSASS access events from non-standard processes on WIN-DC01 · all within jsmith session window · results attached' },
    { type:'reason', agent:'ts',   msg:'rows 2–3 (handle 0x1410) are read-only memory access — benign, typical of monitoring tools · only row 1 (PID 7340, handle 0x1fffff) is PROCESS_ALL_ACCESS — that is the critical hit' },
    { type:'reason', agent:'ts',   msg:'SK-029 criteria applied: PROCESS_ALL_ACCESS (0x1fffff) on lsass.exe from unsigned or LOLBin source · rundll32.exe with no command-line args is consistent with reflective shellcode injection',
      detail:'Handle access breakdown:\n• 0x1fffff (PROCESS_ALL_ACCESS) — full read/write/execute on process memory; used by credential dumpers (Mimikatz, Cobalt Strike in-memory dump)\n• 0x1410 (PROCESS_QUERY_INFORMATION | VM_READ) — read-only; used by AV/monitoring tools, cannot dump credentials\nSK-029 fires only on 0x1fffff from non-AV source images. PID 7340 (rundll32.exe, no args, unsigned) is a LOLBin — exact match to SK-029 evasion pattern.' },
    { type:'warn',   agent:'ts',   msg:'🔴 rundll32.exe opened LSASS with PROCESS_ALL_ACCESS (0x1fffff) on WIN-DC01 at 01:38:22 UTC · risk score 94',
      detail:'rundll32.exe (C:\\Windows\\System32\\rundll32.exe) opened lsass.exe with handle 0x1fffff at 01:38:22 UTC. Process tree: explorer.exe → cmd.exe (PID 4812) → rundll32.exe (PID 7340). No command-line args — consistent with reflective shellcode injection. Matches SK-029 LSASS evasion pattern exactly.' },
    { type:'relay',  agent:'ts',   to:'orch', msg:'🔴 CRITICAL FINDING — LSASS credential dump on Tier-0 DC WIN-DC01 · rundll32 PROCESS_ALL_ACCESS · score 94 · recommend immediate analyst escalation' },
    { type:'relay',  agent:'orch', to:'rv',   msg:'urgent — check deployed Splunk rules: is rundll32→LSASS with handle 0x1fffff on WIN-DC01 currently covered by any active detection?' },
    { type:'tool',   agent:'rv',   msg:'scanning 847 deployed Splunk ES rules for LSASS + rundll32 + PROCESS_ALL_ACCESS coverage…' },
    { type:'relay',  agent:'rv',   to:'orch', msg:'checked all 847 rules — no deployed rule covers rundll32→LSASS with PROCESS_ALL_ACCESS · detection gap confirmed · WIN-DC01 is currently blind to this technique' },
    { type:'relay',  agent:'orch', to:'dl',   msg:'critical gap confirmed by Validation · T1003.001 LSASS on WIN-DC01 is priority-1 rule for Detection Logic · escalating ahead of T1053.005 and T1547.001' },
    { type:'done',   agent:'ts',   msg:'tradecraft complete · T1570 confirmed · T1003.001 confirmed · T1558.003 forwarded · T1071.001 forwarded to Detection Logic',
      detail:'RAA summary:\n• T1570: 59 confirmed hits · jsmith 14-host pivot chain · PASS TO KEEP\n• T1003.001: 1 critical hit · rundll32 LSASS 0x1fffff on WIN-DC01 · PASS TO KEEP\n• T1558.003: 0 hits above tuned threshold after SPN exclusion · needs rule refinement\n• T1071.001: network-layer technique outside RAA scope · forwarded to Detection Logic for JA3 analysis\nAll 4 hypotheses forwarded to Detection Logic for rule generation.' },
  ],
  4: [
    { type:'relay',  agent:'dl',   to:'ts',   msg:'received tradecraft package · confirming FP exclusions for T1003.001 — which process images should I whitelist for LSASS access?' },
    { type:'relay',  agent:'ts',   to:'dl',   msg:'exclude: MsMpEng.exe, csagent.sys, SenseIR.exe, CrowdStrike sensor PID · trigger only on PROCESS_ALL_ACCESS (0x1fffff) from unsigned or LOLBin source',
      detail:'SK-029 exclusion list validated against 6 months of endpoint telemetry. These 4 exclusions reduce FP rate from 34% to under 2% while preserving all known LSASS evasion patterns.' },
    { type:'tool',   agent:'dl',   msg:'generating SPL rule for H-01 · T1570 — PsExec ADMIN$ file drop + service install correlation…' },
    { type:'relay',  agent:'dl',   to:'rv',   msg:'please validate DL-2026-041-001 (T1570-psexec-admin-drop) · SCCM exclusion applied · EventCode=5145 joined with EventCode=7045' },
    { type:'tool',   agent:'rv',   msg:'validating DL-2026-041-001 · schema check · CIM field mapping · FP rate simulation against 30-day baseline…' },
    { type:'relay',  agent:'rv',   to:'dl',   msg:'DL-2026-041-001 PASS · schema OK · FP rate 1.4% confirmed · SCCM host exclusions verified · cleared for deployment' },
    { type:'tool',   agent:'dl',   msg:'generating + submitting rules DL-2026-041-002/003/004 to Rule Validation · T1003.001 (SK-029 exclusions), T1558.003 (147-entry SPN list), T1071.001 (JA3 hash set + beacon stdev < 5s)' },
    { type:'relay',  agent:'rv',   to:'dl',   msg:'DL-2026-041-002 PASS · schema OK · FP rate 0.9% · SK-029 exclusions verified · cleared for deployment' },
    { type:'relay',  agent:'rv',   to:'dl',   msg:'DL-2026-041-003 PASS · schema OK · FP rate 0.4% · all 147 SPN exclusions verified · cleared for deployment' },
    { type:'relay',  agent:'rv',   to:'dl',   msg:'DL-2026-041-004 PASS · schema OK · FP rate 0.2% · JA3 hashes verified against threat intel feed · cleared for deployment' },
    { type:'relay',  agent:'dl',   to:'orch', msg:'all 4 rules validated · DL-2026-041-001 PASS (T1570) · DL-2026-041-002 PASS (T1003.001) · DL-2026-041-003 PASS (T1558.003) · DL-2026-041-004 PASS (T1071.001) · pushing to Splunk ES now' },
    { type:'done',   agent:'dl',   msg:'4 rules deployed to Splunk ES queue · 4 PASS · hunt TH-2026-041 detection coverage active',
      detail:'Deployment summary:\n• DL-2026-041-001 (T1570 — PsExec ADMIN$ drop): PASS · FP 1.4% · severity HIGH\n• DL-2026-041-002 (T1003.001 — LSASS full-access handle): PASS · FP 0.9% · severity CRITICAL\n• DL-2026-041-003 (T1558.003 — Kerberoasting RC4 burst): PASS · FP 0.4% · severity HIGH\n• DL-2026-041-004 (T1071.001 — C2 JA3 beacon): PASS · FP 0.2% · severity CRITICAL\nAll 4 queued in Splunk ES deployment pipeline. No analyst WARN items.' },
  ],
};

const feedStepLabels = ['Select Intel','TTP Extraction','Hypotheses','Tradecraft','Detection Logic'];
let feedTimers = [];

// ── Realism helpers ──────────────────────────────────────────
let _totalTokens = 0;
let _typewriteCancelToken = 0;
let _chainToken = 0; // incremented on step change to break in-progress entry chains
const _tokensPerType = { reason:165, tool:55, relay:40, done:85, warn:65, env:25, runbook:45 };
const _entryDelayBase = { reason:1100, tool:750, relay:550, done:650, warn:850, env:350, runbook:500 };
const _thinkDelayBase = { reason:600, tool:350, relay:200, done:150, warn:480, env:130, runbook:220 };

function _highlightSpl(raw) {
  let s = raw.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  // Quoted strings FIRST — before any spans are injected, so the regex cannot
  // accidentally match class="spl-xxx" attribute values inside later-added spans
  // and corrupt the HTML structure.
  s = s.replace(/"([^"]*?)"/g,'<span class="spl-val">"$1"</span>');
  // Commands (before keywords so "stats count" hits command first)
  ['stats','timechart','chart','table','top','rare','bucket','eval','rex','rename','dedup','sort','head','tail','transaction','lookup','inputlookup','outputlookup','collect','sendemail','anomalydetection'].forEach(c => {
    s = s.replace(new RegExp('\\b(' + c + ')\\b','gi'), '<span class="spl-cmd">$1</span>');
  });
  // Keywords (note: 'span' intentionally excluded — matches HTML element name)
  ['index','source','sourcetype','host','earliest','latest','where','search','fields','by','as','values','count','sum','avg','min','max','dc','list','filter'].forEach(k => {
    s = s.replace(new RegExp('\\b(' + k + ')\\b','gi'), '<span class="spl-kw">$1</span>');
  });
  // Pipes
  s = s.replace(/\|/g,'<span class="spl-pipe">|</span>');
  // field=value (not followed by " so span attributes are skipped)
  s = s.replace(/([a-zA-Z_]\w*)=(?!")/g,'<span class="spl-fld">$1</span>=');
  return s;
}

// Copy raw text from the nearest <pre> inside the same .feed-spl wrapper (used by static HTML blocks)
function _copySplFromPre(btn) {
  const pre = btn.closest('.feed-spl')?.querySelector('pre');
  if (pre) _copySpl(btn, pre.textContent.trim());
}

function _copySpl(btn, text) {
  navigator.clipboard.writeText(text).then(() => {
    const orig = btn.textContent;
    btn.textContent = '✓ copied';
    setTimeout(() => { btn.textContent = orig; }, 1400);
  }).catch(() => {});
}

function _addThinking(agent) {
  const feed = document.getElementById('agents-reasoning-feed');
  if (!feed) return null;
  const empty = document.getElementById('agents-feed-empty');
  if (empty) empty.remove();
  const ag  = feedAgents[agent] || { icon:'🤖', name:'Agent' };
  const col = feedAgentColors[agent] || { bg:'rgba(148,163,184,.15)', border:'#94a3b8' };
  const el  = document.createElement('div');
  el.className  = 'feed-thinking';
  el.dataset.agent = agent;
  el.innerHTML  = `<div class="feed-thinking-av" style="background:${col.bg};border:1px solid ${col.border};">${ag.icon}</div><div class="feed-thinking-dots"><span></span><span></span><span></span></div>`;
  feed.appendChild(el);
  feed.scrollTop = feed.scrollHeight;
  return el;
}

function _typewrite(el, text, speed, onDone) {
  // Snapshot token — do NOT increment (only clearAgentsFeed increments to
  // cancel everything at once). Ticks use raw setTimeout so they are NOT
  // stored in feedTimers and cannot be killed by a step transition.
  const tok = _typewriteCancelToken;
  let i = 0;
  const tick = () => {
    if (_typewriteCancelToken !== tok) {
      el.textContent = text; // complete instantly rather than leaving half-typed
      if (onDone) onDone();
      return;
    }
    if (i < text.length) {
      el.textContent += text[i++];
      setTimeout(tick, i < 10 ? speed * 3 : speed); // raw — immune to feedTimers.forEach(clearTimeout)
    } else {
      if (onDone) onDone();
    }
  };
  tick();
}

const _microState = {
  tool:    'querying…',
  reason:  'reasoning…',
  done:    'done',
  warn:    '⚠ flagging',
  env:     'env lookup…',
  runbook: 'loading…',
};

// Relative-timestamp updater (runs every 20s)
setInterval(() => {
  document.querySelectorAll('.feed-block[data-ts], .feed-block-relay[data-ts]').forEach(block => {
    const age = Math.floor((Date.now() - parseInt(block.dataset.ts, 10)) / 1000);
    if (age < 15) return;
    const tsEl = block.querySelector('.feed-ts-text');
    if (tsEl) tsEl.textContent = age < 60 ? `${age}s ago ` : age < 3600 ? `${Math.floor(age/60)}m ago ` : `${Math.floor(age/3600)}h ago `;
  });
}, 20000);

function feedAddSep(label) {
  feedAddBlockSep(label);
}

function feedAddEntry(e, onComplete) {
  const { type, agent, to } = e;

  // Micro-state label
  const label = to ? `→ ${feedAgents[to]?.name || to}` : (_microState[type] || 'active');
  _setAgentLegendStatus(agent, label);
  if (to) _setAgentLegendStatus(to, 'receiving…');

  pulseTopoNode(agent);
  if (to) {
    setTimeout(() => pulseTopoNode(to), 200);
    pulseTopoLine(agent === 'orch' ? to : agent);
    // Secondary line pulse for direct inter-agent messages (neither side is orch)
    if (agent !== 'orch' && to !== 'orch') pulseSecondaryLine(agent, to);
  } else {
    pulseTopoLine(agent);
  }

  // Thinking indicator then stream the block
  const thinkEl  = _addThinking(agent);
  const thinkMs  = (_thinkDelayBase[type] || 300) + Math.random() * 200;
  feedTimers.push(setTimeout(() => {
    if (thinkEl && thinkEl.parentNode) thinkEl.remove();
    feedAddBlock(e, true, onComplete);
    if (type === 'done') _setAgentLegendStatus(agent, 'idle');
  }, thinkMs));
}

// ── Big agents reasoning feed ──
let activeFeedFilter = 'all';
let _stepStartTime   = 0;

function feedAddBlock(e, doStream = false, onDone) {
  const { type, agent, msg, detail, to } = e;
  const feed = document.getElementById('agents-reasoning-feed');
  if (!feed) return;
  const empty = document.getElementById('agents-feed-empty');
  if (empty) empty.remove();

  const ag      = feedAgents[agent] || { icon:'🤖', name:'Agent' };
  const col     = feedAgentColors[agent] || { bg:'rgba(148,163,184,.15)', border:'#94a3b8' };
  const now     = new Date();
  const tsStr   = `${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;
  const elapsed = _stepStartTime ? ` +${((Date.now() - _stepStartTime) / 1000).toFixed(1)}s` : '';
  const badge   = feedBadgeLabels[type] || type.toUpperCase();
  const tsMark  = `<span class="feed-block-ts"><span class="feed-ts-text">${tsStr} </span><span class="feed-block-elapsed">${elapsed}</span></span>`;

  let headHtml;
  if (type === 'relay' && to) {
    const toAg  = feedAgents[to] || { icon:'🤖', name:'Agent' };
    const toCol = feedAgentColors[to] || { bg:'rgba(148,163,184,.15)', border:'#94a3b8' };
    headHtml = `<div class="feed-block-avatar" style="background:${col.bg};border:1px solid ${col.border};">${ag.icon}</div>
      <span class="feed-block-name">${ag.name}</span>
      <span class="feed-relay-arrow">→</span>
      <div class="feed-block-avatar" style="background:${toCol.bg};border:1px solid ${toCol.border};">${toAg.icon}</div>
      <span class="feed-block-name feed-block-name-to">${toAg.name}</span>
      <span class="feed-block-badge fb-relay">${badge}</span>${tsMark}`;
  } else {
    headHtml = `<div class="feed-block-avatar" style="background:${col.bg};border:1px solid ${col.border};">${ag.icon}</div>
      <span class="feed-block-name">${ag.name}</span>
      <span class="feed-block-badge fb-${type}">${badge}</span>${tsMark}`;
  }

  const el = document.createElement('div');
  el.className     = type === 'relay' ? 'feed-block feed-block-relay' : 'feed-block';
  el.dataset.agent = agent;
  el.dataset.to    = to || '';
  el.dataset.ts    = Date.now();

  if (activeFeedFilter !== 'all' && el.dataset.agent !== activeFeedFilter && el.dataset.to !== activeFeedFilter) {
    el.style.display = 'none';
  }

  el.innerHTML = `<div class="feed-block-head">${headHtml}</div>`;

  // Message element — streamed or instant
  const msgEl = document.createElement('div');
  msgEl.className = 'feed-block-msg';
  el.appendChild(msgEl);

  // Detail (hidden until toggled)
  if (detail) {
    const btn = document.createElement('button');
    btn.className = 'feed-block-toggle';
    btn.textContent = '▼ details';
    btn.setAttribute('onclick', 'toggleFeedDetail(this)');
    el.appendChild(btn);
    const div = document.createElement('div');
    div.className = 'feed-block-detail';
    div.style.display = 'none';
    div.innerHTML = detail.replace(/\n/g, '<br>');
    el.appendChild(div);
  }

  // SPL block with syntax highlighting + copy button
  if (e.spl) {
    const splWrap = document.createElement('div');
    splWrap.className = 'feed-spl';
    const copyBtn = document.createElement('button');
    copyBtn.className = 'spl-copy';
    copyBtn.textContent = 'copy';
    copyBtn.addEventListener('click', () => _copySpl(copyBtn, e.spl));
    const head = document.createElement('div');
    head.className = 'feed-spl-head';
    head.innerHTML = '<span class="feed-spl-label">SPL</span>';
    head.appendChild(copyBtn);
    const pre = document.createElement('pre');
    pre.className = 'feed-spl-pre';
    pre.innerHTML = _highlightSpl(e.spl);
    splWrap.appendChild(head);
    splWrap.appendChild(pre);
    el.appendChild(splWrap);
  }

  // Results micro-table
  if (e.results) {
    const { cols, rows } = e.results;
    const rWrap = document.createElement('div');
    rWrap.className = 'feed-results';
    rWrap.innerHTML = `<table class="feed-results-table"><thead><tr>${cols.map(c => `<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
    el.appendChild(rWrap);
  }

  // Visual grouping: consecutive messages from the same agent+direction merge into one card
  const prevBlock = feed.lastElementChild;
  if (prevBlock &&
      prevBlock.classList.contains('feed-block') &&
      !prevBlock.classList.contains('feed-block-sep') &&
      prevBlock.dataset.agent === agent &&
      prevBlock.dataset.to === (to || '')) {
    el.classList.add('feed-block-continued');
    prevBlock.classList.add('feed-block-precedes-continued');
  }

  feed.appendChild(el);
  feed.scrollTop = feed.scrollHeight;

  if (doStream) {
    const speed = type === 'reason' ? 7 : type === 'warn' ? 8 : 4;
    _typewrite(msgEl, msg, speed, onDone);
  } else {
    msgEl.textContent = msg;
    if (onDone) onDone();
  }

  // Token counter
  _totalTokens += (_tokensPerType[type] || 50) + Math.floor(Math.random() * 15);
  const tokEl = document.getElementById('feed-token-count');
  if (tokEl) {
    tokEl.style.display = '';
    tokEl.textContent = `~${_totalTokens.toLocaleString()} tok`;
  }
}

function setFeedFilter(agent, btn) {
  activeFeedFilter = agent;
  document.querySelectorAll('.ffp').forEach(b => b.classList.remove('ffp-on'));
  if (btn) btn.classList.add('ffp-on');
  const feed = document.getElementById('agents-reasoning-feed');
  if (!feed) return;
  feed.querySelectorAll('.feed-block, .feed-block-relay').forEach(block => {
    if (agent === 'all') {
      block.style.display = '';
    } else {
      block.style.display = (block.dataset.agent === agent || block.dataset.to === agent) ? '' : 'none';
    }
  });
  // always show separators when filtering (context anchors)
  feed.querySelectorAll('.feed-block-sep').forEach(sep => { sep.style.display = ''; });
}

function feedAddBlockSep(label) {
  const feed = document.getElementById('agents-reasoning-feed');
  if (!feed) return;
  const el = document.createElement('div');
  el.className = 'feed-block-sep';
  el.innerHTML = `<div class="feed-block-sep-line"></div><span class="feed-block-sep-label">${label}</span><div class="feed-block-sep-line"></div>`;
  feed.appendChild(el);
  feed.scrollTop = feed.scrollHeight;
}

function clearAgentsFeed() {
  // Stop in-progress entry chain and all typewriters
  _chainToken++;
  _typewriteCancelToken++;
  const feed = document.getElementById('agents-reasoning-feed');
  if (!feed) return;
  feed.innerHTML = `<div class="agents-feed-empty" id="agents-feed-empty">
    <div style="font-size:32px;margin-bottom:12px;opacity:.25;">🤖</div>
    <div style="font-size:13px;font-weight:600;color:var(--sub);margin-bottom:7px;">No reasoning activity yet</div>
    <div style="font-size:11px;color:var(--muted);max-width:280px;line-height:1.6;">Step through the LOCK pipeline tabs to watch agents reason, collaborate, and make decisions in real time.</div>
  </div>`;
  const dot     = document.getElementById('agents-feed-dot');
  const statusEl = document.getElementById('agents-feed-status');
  const tokEl   = document.getElementById('feed-token-count');
  if (dot) dot.style.opacity = '0.3';
  if (statusEl) statusEl.textContent = 'Waiting for pipeline…';
  if (tokEl) { tokEl.style.display = 'none'; tokEl.textContent = '~0 tok'; }
  _totalTokens = 0;
  // Reset legend
  ['orch','hyp','data','ts','dl'].forEach(a => _setAgentLegendStatus(a, 'idle'));
  // Reset pipeline steps
  for (let i = 0; i < 5; i++) _setAgentProgStep(i, 'pending');
  // Reset filter to All
  _stepStartTime = 0;
  activeFeedFilter = 'all';
  setFeedFilter('all', document.querySelector('.ffp'));
}

function _setAgentLegendStatus(agent, status) {
  // Agent Status card row
  const el = document.getElementById('aleg-' + agent + '-s');
  if (el) {
    el.textContent = status;
    el.style.color = status === 'idle'       ? 'var(--muted)'
                   : status === 'done'       ? 'var(--blue)'
                   : status === 'reasoning…' ? '#a5b4fc'
                   : status === 'querying…'  ? 'var(--blue)'
                   : status === 'receiving…' ? 'var(--teal)'
                   : status.startsWith('→')  ? 'var(--teal)'
                   : status.startsWith('⚠') ? 'var(--red)'
                   : 'var(--green)';
  }
  // Topology live label
  const lbl = document.getElementById('topo-lbl-' + agent);
  if (lbl) lbl.textContent = (status === 'idle' || status === 'done') ? '' : status;
  // Topology status ring
  const ring = document.getElementById('topo-r-' + agent);
  if (ring) {
    const active = status !== 'idle' && status !== 'done';
    ring.setAttribute('opacity', active ? '1' : '0');
    if (active) ring.classList.add('topo-ring-active');
    else ring.classList.remove('topo-ring-active');
  }
}

function _setAgentProgStep(step, state) {
  const el = document.getElementById('aprog-' + step);
  if (!el) return;
  const dot = el.querySelector('.aprog-dot');
  if (state === 'active') { el.style.color = 'var(--blue)'; if (dot) dot.textContent = '●'; }
  else if (state === 'done') { el.style.color = 'var(--green)'; if (dot) dot.textContent = '✓'; }
  else { el.style.color = 'var(--muted)'; if (dot) dot.textContent = '○'; }
}

function toggleFeedDetail(btn) {
  const detail = btn.nextElementSibling;
  const isOpen = detail.style.display !== 'none';
  detail.style.display = isOpen ? 'none' : '';
  btn.textContent = isOpen ? '▼ details' : '▲ hide';
}

// ── Topology node / line pulse ──
const _topoLineMap = {
  'hyp':'topo-l-hyp','data':'topo-l-data','ts':'topo-l-ts','dl':'topo-l-dl'
};
// Secondary inter-agent lines (keyed as "from-to" both orders resolve to same line)
const _topoSecMap = {
  'hyp-ts':'topo-sl-hyp-ts', 'ts-hyp':'topo-sl-hyp-ts',
  'ts-data':'topo-sl-ts-data','data-ts':'topo-sl-ts-data',
  'dl-ts':'topo-sl-dl-ts',   'ts-dl':'topo-sl-dl-ts',
};
function pulseSecondaryLine(from, to) {
  const el = document.getElementById(_topoSecMap[from + '-' + to]);
  if (!el) return;
  el.classList.remove('topo-sec-lit');
  void el.getBoundingClientRect();
  el.classList.add('topo-sec-lit');
  setTimeout(() => el.classList.remove('topo-sec-lit'), 1200);
}
function pulseTopoNode(agent) {
  const el = document.getElementById('topo-c-' + agent);
  if (!el) return;
  el.classList.remove('topo-node-lit');
  void el.getBoundingClientRect();
  el.classList.add('topo-node-lit');
  setTimeout(() => el.classList.remove('topo-node-lit'), 1400);
}
function pulseTopoLine(agent) {
  const lineId = _topoLineMap[agent];
  if (!lineId) return;
  // Flash line color
  const el = document.getElementById(lineId);
  if (el) {
    el.classList.remove('topo-line-lit');
    void el.getBoundingClientRect();
    el.classList.add('topo-line-lit');
    setTimeout(() => el.classList.remove('topo-line-lit'), 1000);
  }
  // Traveling dot along the line
  const dot = document.getElementById('topo-dot-' + agent);
  const am  = document.getElementById('topo-am-'  + agent);
  if (dot && am) {
    dot.setAttribute('opacity', '0.9');
    try { am.beginElement(); } catch(e) {}
    setTimeout(() => dot.setAttribute('opacity', '0'), 400);
  }
}

function topoFilterFeed(agent) {
  let matchPill = null;
  document.querySelectorAll('.ffp').forEach(b => {
    const oc = b.getAttribute('onclick') || '';
    if (oc.includes(`'${agent}'`)) matchPill = b;
  });
  setFeedFilter(agent, matchPill);
}

function playFeedStep(step) {
  feedTimers.forEach(clearTimeout);
  feedTimers = [];
  // Break any in-progress chain from a previous step
  _chainToken++;
  const myChain = _chainToken;
  _stepStartTime = Date.now();
  const entries = feedSteps[step] || [];

  // Drive agents-feed header
  const dot      = document.getElementById('agents-feed-dot');
  const agStatus = document.getElementById('agents-feed-status');
  if (dot) dot.style.opacity = '1';
  if (agStatus) agStatus.textContent = 'streaming — ' + (feedStepLabels[step] || 'Step ' + step);
  _setAgentProgStep(step, 'active');

  feedAddSep(feedStepLabels[step] || 'Step ' + step);

  // Sequential chain: each entry appears only after the previous typewriter
  // finishes, then a short inter-message gap before the next entry's think
  // indicator appears. This prevents messages from being interrupted and gives
  // each message room to breathe before the next one arrives.
  let i = 0;
  const _interGap = { reason:280, tool:180, relay:150, done:220, warn:260, env:120, runbook:170 };

  const scheduleNext = () => {
    if (_chainToken !== myChain) return; // step changed — stop this chain
    if (i >= entries.length) {
      feedTimers.push(setTimeout(() => {
        if (_chainToken !== myChain) return;
        if (dot) dot.style.opacity = '0.4';
        if (agStatus) agStatus.textContent = 'idle · last: ' + (feedStepLabels[step] || 'Step ' + step);
        _setAgentProgStep(step, 'done');
        ['orch','hyp','data','ts','dl'].forEach(a => _setAgentLegendStatus(a, 'idle'));
      }, 500));
      return;
    }
    const e = entries[i++];
    const gap = (_interGap[e.type] || 220) + Math.random() * 160;
    feedTimers.push(setTimeout(() => {
      if (_chainToken !== myChain) return;
      feedAddEntry(e, scheduleNext);
    }, gap));
  };

  scheduleNext();
}

function setStep(i) {
  if (pipelineLocked) return; // closed hunt — pipeline is read-only
  const isForward = i > maxStep;
  maxStep = Math.max(maxStep, i);
  for (let j = 0; j < 5; j++) {
    const n = document.getElementById('ps' + j);
    if (n) n.className = 'ps-node ' + (j === i ? 'curr' : j < i || j < maxStep ? 'done' : 'wait');
    if (j < 4) {
      const l = document.getElementById('pl' + j);
      if (l) l.className = 'ps-line' + (j < i || j < maxStep ? ' done' : '');
    }
    const s = document.getElementById('stage-' + j);
    if (s) s.className = 'stage card' + (j <= i ? ' show' : '');
  }
  updateAgentPills(maxStep);
  const stageLabels = ['Learn · Select Intel', 'Learn · TTP Extraction', 'Learn · Hypotheses', 'Learn · Tradecraft', 'Learn · Detection'];
  const stageEl = document.getElementById('lhc-stage');
  if (stageEl) stageEl.textContent = stageLabels[i] || stageLabels[0];
  if (maxStep >= 2) {
    const hypEl = document.getElementById('lhc-hyp');
    if (hypEl) { hypEl.textContent = '4 generated'; hypEl.style.color = ''; }
    const pastCard = document.getElementById('learn-past-card');
    if (pastCard) pastCard.style.display = '';
    // Reveal subhunt sidebar — hypotheses are now generated
    const huntId = document.getElementById('hd-id')?.textContent || '';
    if (huntId && typeof renderSubhuntSidebar === 'function') renderSubhuntSidebar(huntId);
  }
  if (isForward) playFeedStep(i);
  if (typeof updateSubTabGating === 'function') updateSubTabGating();
  // Scroll to the target stage (auto-expand if collapsed)
  const stageTarget = document.getElementById('stage-' + i);
  if (stageTarget) {
    stageTarget.classList.remove('collapsed');
    setTimeout(() => stageTarget.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50);
  }
}

// ── Reset pipeline state when switching hunts ──
function resetPipeline() {
  feedTimers.forEach(clearTimeout);
  feedTimers = [];
  maxStep = -1;
  pipelineLocked = false;
  // Remove locked class from pipeline
  const pipelineEl = document.querySelector('.pipeline');
  if (pipelineEl) pipelineEl.classList.remove('pipeline-locked');
  clearAgentsFeed();
  for (let j = 0; j < 5; j++) {
    const n = document.getElementById('ps' + j);
    if (n) n.className = 'ps-node ' + (j === 0 ? 'curr' : 'wait');
    if (j < 4) {
      const l = document.getElementById('pl' + j);
      if (l) l.className = 'ps-line';
    }
    const s = document.getElementById('stage-' + j);
    if (s) s.className = 'stage card' + (j === 0 ? ' show' : '');
  }
  updateAgentPills(0);
  const stageEl = document.getElementById('lhc-stage');
  if (stageEl) stageEl.textContent = 'Learn · Select Intel';
  const hypEl = document.getElementById('lhc-hyp');
  if (hypEl) { hypEl.textContent = '—'; hypEl.style.color = 'var(--muted)'; }
  const pastCard = document.getElementById('learn-past-card');
  if (pastCard) pastCard.style.display = 'none';
  // Hide subhunt sidebar until hypotheses are generated (step 2)
  const sidebar = document.getElementById('subhunt-sidebar');
  if (sidebar) sidebar.style.display = 'none';
  // Re-gate sub-tabs for fresh active hunt
  if (typeof updateSubTabGating === 'function') updateSubTabGating();
  const feedStatus = document.getElementById('feed-status');
  if (feedStatus) feedStatus.textContent = 'idle';

  // Restore Stage 0 + Stage 1 DOM that loadClosedPipeline may have mutated
  // Re-show any elements that were hidden (marked with data-archived-hidden)
  document.querySelectorAll('[data-archived-hidden]').forEach(el => {
    el.removeAttribute('data-archived-hidden');
    el.style.display = '';
  });
  // Re-render repo list to restore interactive card list
  if (typeof renderRepo === 'function' && typeof repoData !== 'undefined') renderRepo(repoData);
  // Restore original TTP table rows
  const ttpTb = document.getElementById('ttp-tbody');
  if (ttpTb && _origTtpTbody) ttpTb.innerHTML = _origTtpTbody;
  // Restore Stage 0 info-bar
  const s0ib = document.querySelector('#stage-0 .info-bar');
  if (s0ib && _origStage0InfoBar) s0ib.innerHTML = _origStage0InfoBar;
  // Restore Stage 1 info-bar
  const s1ib = document.querySelector('#stage-1 .info-bar');
  if (s1ib && _origStage1InfoBar) s1ib.innerHTML = _origStage1InfoBar;
  // Reset repo-loaded-badge
  const badge = document.getElementById('repo-loaded-badge');
  if (badge) badge.style.display = 'none';
  const s0sum = document.getElementById('stage-0-summary-text');
  if (s0sum) s0sum.innerHTML = '<span style="color:var(--muted);font-style:italic;">No report selected — expand to browse</span>';
}

// ── Pre-baked feed archives for closed hunts ──
const closedHuntFeeds = {
  '040': [
    { sep: 'Select Intel' },
    { type:'tool',   agent:'orch', msg:'pipeline initialised for TH-2026-040 · FS-ISAC TLP:AMBER FIN7 advisory · 9 TTPs queued · Finance segment scope' },
    { type:'tool',   agent:'data', msg:'connected to Splunk ES · 4 indices confirmed · security(90d) wineventlog(30d) sysmon(7d) · CIM normalised · ready' },
    { sep: 'TTP Extraction' },
    { type:'reason', agent:'hyp',  msg:'9 TTPs extracted from FS-ISAC advisory · scored by confidence + kill chain position + coverage gap',
      detail:'Confidence scores:\n• T1566.001 — 88% (TA577 IOC match, prior hunt TH-2025-088)\n• T1490 — 85% (FIN7 TTPs consistently include pre-encryption staging)\n• T1204 — 84% (dependent on T1566.001 delivery succeeding)\n• T1486 — 79% (post-staging, requires T1490 to precede)\n• T1574.002 — 76% (persistence mechanism, lower urgency)\n• T1003.001, T1071.001, T1547.001, T1053.005 — 55–68% · existing live rules cover these' },
    { type:'tool',   agent:'data', msg:'Finance segment baseline complete · 1.2M events in scope · spike threshold set · EventCode=4688, 7, 1 indexed' },
    { type:'reason', agent:'orch', msg:'scope decision: 2 of 9 TTPs selected for hypothesis generation — T1566.001 + T1490',
      detail:'Selection rationale:\n• T1566.001 (Phishing macro): confidence 88% · initial access vector — foundational, all downstream TTPs depend on this succeeding · TA577 IOC confirmed by FS-ISAC · no prior Finance-scoped detection rule\n• T1490 (Shadow copy deletion): confidence 85% · no existing detection rule · critical business impact (Finance file server = payroll data) · FIN7 kill chain signature — if T1566.001 lands, T1490 is the next high-value hunt target\n\nDeferred from scope:\n• T1204 — covered within T1566.001 hypothesis (same delivery chain)\n• T1486 — post-staging; detection value requires T1490 confirmation first\n• T1574.002 — low signal; no sideloading incidents in Finance baseline\n• T1003.001, T1071.001, T1547.001, T1053.005 — existing live rules active · no coverage gap' },
    { sep: 'Hypotheses' },
    { type:'reason', agent:'hyp',  msg:'🎯 H-01 (T1566.001): phishing macro delivery · confidence 88% · initial access vector · TA577 IOC confirmed',
      detail:'Prior hunt TH-2025-088 confirmed TA577 attribution in Finance segment. Office macro execution chain (vba→cmd→rundll32) is the expected delivery vector per FS-ISAC indicators. Scope: Finance segment endpoints, EventCode=4688 with Office parent process.' },
    { type:'reason', agent:'hyp',  msg:'🔴 H-02 (T1490): ransomware pre-staging · confidence 85% · no detection rule · critical business impact',
      detail:'FIN7 consistently deletes Volume Shadow Copies before deploying ransomware payload. No existing rule covers this on Finance file servers. Payroll data at risk if T1566.001 hypothesis is confirmed. Scope: WIN-FS02 + Finance file servers, vssadmin.exe with delete shadows /all args.' },
    { type:'relay',  agent:'orch', to:'ts',  msg:'2 hypotheses analyst-approved · T1566.001 (delivery) + T1490 (staging) · begin tradecraft analysis' },
    { sep: 'Tradecraft' },
    { type:'reason', agent:'ts',   msg:'T1566.001 macro chain confirmed · WIN-WS012 · vba→cmd→rundll32.exe parent chain · 12 process chain hits across 3 hosts' },
    { type:'warn',   agent:'ts',   msg:'🔴 T1490 CRITICAL — vssadmin delete shadows /all on WIN-FS02 at 14:22 UTC · anomaly score 97 · ransomware staging confirmed',
      detail:'vssadmin.exe executed with full shadow deletion args from DISM.exe parent (sideloaded). Score 97. Followed by Cipher.exe activity on \\payroll$ share at 14:25. Recommend immediate isolation of WIN-FS02.' },
    { type:'relay',  agent:'orch', to:'ts',  msg:'WIN-FS02 isolation escalated to analyst · continue to detection logic' },
    { sep: 'Detection Logic' },
    { type:'tool',   agent:'dl',   msg:'generating 5 SPL rules · T1566.001, T1204, T1574.002, T1486, T1490 · Finance segment scope · SCCM exclusions applied' },
    { type:'relay',  agent:'dl',   to:'rv',  msg:'validate all 5 rules · DL-2026-040-001 through 005 · FP targets: < 3% each' },
    { type:'relay',  agent:'rv',   to:'dl',  msg:'all 5 PASS · 001(T1566.001 FP 2.1%) · 002(T1490 FP 0.3%) · 003(T1204 FP 1.8%) · 004(T1574.002 FP 2.4%) · 005(T1486 FP 0.6%)' },
    { type:'done',   agent:'dl',   msg:'5 rules deployed to Splunk ES · hunt TH-2026-040 archived · 2 hypotheses confirmed · 6 findings documented',
      detail:'Deployment summary:\n• DL-2026-040-001 (T1566.001 — Office macro exec): PASS · FP 2.1% · severity HIGH\n• DL-2026-040-002 (T1490 — vssadmin shadow deletion): PASS · FP 0.3% · severity CRITICAL\n• DL-2026-040-003 (T1204 — user execution macro): PASS · FP 1.8% · severity HIGH\n• DL-2026-040-004 (T1574.002 — DISM sideload): PASS · FP 2.4% · severity HIGH\n• DL-2026-040-005 (T1486 — file encryption pattern): PASS · FP 0.6% · severity CRITICAL' },
  ],
  '039': [
    { sep: 'Select Intel' },
    { type:'tool',   agent:'orch', msg:'pipeline initialised for TH-2026-039 · CISA Supply Chain Advisory · 7 TTPs queued · DevOps pipeline + all endpoints scope' },
    { type:'tool',   agent:'data', msg:'connected to Splunk ES · 4 indices confirmed · sysmon(7d) wineventlog(30d) network(14d) · artifact registry hash list loaded · ready' },
    { sep: 'TTP Extraction' },
    { type:'reason', agent:'hyp',  msg:'7 TTPs extracted from CISA advisory · scored by confidence + coverage gap + blast-radius impact',
      detail:'Confidence scores:\n• T1195.002 — 84% (SolarWinds-pattern match, binary signing absent on CI/CD)\n• T1071.001 — 71% (Cobalt Strike malleable profile indicators in advisory)\n• T1574.002 — 68% (DLL sideloading common in supply chain implants)\n• T1053.005 — 65% (scheduled task persistence, 1 existing rule)\n• T1041 — 55% (post-C2 stage, low signal without C2 confirmed)\n• T1547.001 — 58% (registry persistence, existing rule active)\n• T1566.001 — 52% (phishing possible but low signal in DevOps context)' },
    { type:'tool',   agent:'data', msg:'DevOps segment + all endpoints baseline complete · 870K events in scope · artifact registry cross-reference ready' },
    { type:'reason', agent:'orch', msg:'scope decision: 2 of 7 TTPs selected for hypothesis generation — T1195.002 + T1071.001',
      detail:'Selection rationale:\n• T1195.002 (Supply chain compromise): confidence 84% · root cause — if the build artifact is trojanised, all downstream TTPs follow from it · no prior hunt or active detection rule · widest blast radius (10+ downstream hosts)\n• T1071.001 (C2 via HTTPS): confidence 71% · most dangerous active threat once implant is deployed · JA3 fingerprint detection path available (Cobalt Strike malleable profile) · if confirmed, enables immediate containment before lateral movement\n\nDeferred from scope:\n• T1574.002 — downstream of T1195.002; will be covered within blast-radius scope of H-01\n• T1053.005 — existing rule active; no coverage gap\n• T1041 — post-C2 stage; requires H-02 (T1071.001) confirmation first\n• T1547.001 — existing rule active; no coverage gap\n• T1566.001 — active rule + low signal in DevOps segment baseline' },
    { sep: 'Hypotheses' },
    { type:'reason', agent:'hyp',  msg:'🎯 H-01 (T1195.002): trojanised build artifact on SRV-BUILD01 · confidence 84% · root cause · no existing rule',
      detail:'CI/CD pipeline has no binary signing enforcement. Unsigned binary introduced into build output propagates to all downstream hosts pulling from SRV-BUILD01. Detection: Sysmon file-creation events on SRV-BUILD01 cross-referenced against artifact registry hashes. Scope: SRV-BUILD01 + all hosts in DevOps segment.' },
    { type:'reason', agent:'hyp',  msg:'🔴 H-02 (T1071.001): Cobalt Strike C2 via HTTPS · confidence 71% · JA3 detection path · active threat if H-01 confirmed',
      detail:'If SRV-BUILD01 is compromised, an implant establishes C2 via HTTPS using a Cobalt Strike Malleable profile. JA3 fingerprinting on outbound HTTPS from SRV-BUILD01 is the primary detection path. Short-lived Let\'s Encrypt cert + non-browser UA + 60s beacon interval are the anomaly indicators.' },
    { type:'relay',  agent:'orch', to:'ts',  msg:'2 hypotheses analyst-approved · T1195.002 (root cause) + T1071.001 (active C2) · begin tradecraft analysis' },
    { sep: 'Tradecraft' },
    { type:'reason', agent:'ts',   msg:'T1195.002 confirmed · unsigned binary introduced Apr 10 on SRV-BUILD01 · SHA-256 mismatch vs artifact registry · 8 process chain hits' },
    { type:'warn',   agent:'ts',   msg:'🔴 T1071.001 CRITICAL — Cobalt Strike C2 confirmed · JA3 match to update.cdn-cache[.]net · beacon 60s · implant active since Apr 10',
      detail:'JA3 fingerprint 769c10b0 matches Cobalt Strike malleable profile. Beacon interval 60.0 ± 0.3s to update.cdn-cache[.]net:443. Session active since Apr 10 — same day as trojanised binary introduction. 10 downstream hosts at risk.' },
    { type:'relay',  agent:'orch', to:'ts',  msg:'SRV-BUILD01 isolation escalated to analyst · continue to detection logic' },
    { sep: 'Detection Logic' },
    { type:'tool',   agent:'dl',   msg:'generating 4 SPL rules · T1195.002, T1574.002, T1071.001, T1053.005 · build server + endpoint scope · signed-binary exclusions applied' },
    { type:'relay',  agent:'dl',   to:'rv',  msg:'validate all 4 rules · DL-2026-039-001 through 004 · FP targets: < 2% each' },
    { type:'relay',  agent:'rv',   to:'dl',  msg:'all 4 PASS · 001(T1195.002 FP 0.8%) · 002(T1574.002 FP 1.2%) · 003(T1071.001 FP 0.3%) · 004(T1053.005 FP 1.6%)' },
    { type:'done',   agent:'dl',   msg:'4 rules deployed to Splunk ES · hunt TH-2026-039 archived · 2 hypotheses confirmed · 5 findings documented',
      detail:'Deployment summary:\n• DL-2026-039-001 (T1195.002 — unsigned build artifact): PASS · FP 0.8% · severity CRITICAL\n• DL-2026-039-002 (T1574.002 — DLL sideloading): PASS · FP 1.2% · severity HIGH\n• DL-2026-039-003 (T1071.001 — CS C2 JA3 beacon): PASS · FP 0.3% · severity CRITICAL\n• DL-2026-039-004 (T1053.005 — scheduled task persistence): PASS · FP 1.6% · severity HIGH' },
  ],
  '042': [
    { sep: 'Select Intel' },
    { type:'tool',   agent:'orch', msg:'pipeline initialised for TH-2026-042 · seeded from TH-2026-041 follow-up recommendation · 3 TTPs scoped · Tier-0 DC focus' },
    { type:'tool',   agent:'data', msg:'connected to Splunk ES · 4 indices confirmed · security(90d) wineventlog(30d) sysmon(7d) · CIM normalised · ready' },
    { sep: 'TTP Extraction' },
    { type:'reason', agent:'hyp',  msg:'3 TTPs extracted from TH-2026-041 follow-up · all scoped for hypothesis generation — T1078.002, T1484.001, T1003.006',
      detail:'Seeded from confirmed CORP\\jsmith pivot chain. Focus: privileged account abuse post-lateral-movement.\n• T1078.002 (Privileged Account Abuse) — 95% · jsmith authenticated to WIN-DC01 with Domain Admin rights\n• T1484.001 (Domain Policy Modification) — 78% · check for delegation changes or new SPN registrations on Tier-0 accounts\n• T1003.006 (DCSync) — 82% · check for DRS replication requests from non-DC sources' },
    { type:'tool',   agent:'data', msg:'Tier-0 baseline complete · 890K events in scope · EventCode 4662/4672/4768 indexed · WIN-DC01 + WIN-DC02 in scope' },
    { type:'reason', agent:'orch', msg:'scope decision: all 3 TTPs selected for hypothesis generation — follow-up scope from TH-2026-041',
      detail:'All 3 TTPs are directly seeded from the confirmed TH-2026-041 attack chain. No triage needed — this is a targeted follow-up hunt, not a broad CTI sweep.' },
    { sep: 'Hypotheses' },
    { type:'reason', agent:'hyp',  msg:'🎯 H-01 (T1078.002): privileged account abuse · confidence 95% · jsmith Domain Admin auth on WIN-DC01 confirmed',
      detail:'CORP\\jsmith authenticated to WIN-DC01 with Domain Admin rights during the attack window. Enumerate all accounts that authenticated from WIN-DC01 in the 72h prior to detection. Cross-reference against AD for unusual delegation assignments.' },
    { type:'reason', agent:'hyp',  msg:'🔔 H-02 (T1484.001): domain policy modification · confidence 78% · check for delegation and SPN changes on Tier-0',
      detail:'If the attacker gained DC access, they may have modified AD delegation or registered new SPNs to enable DCSync or Golden Ticket attacks. Scope: AD change audit logs, SPN registration events on all Tier-0 accounts.' },
    { type:'reason', agent:'hyp',  msg:'🔴 H-03 (T1003.006): DCSync · confidence 82% · check for DRS replication requests from non-DC sources',
      detail:'DCSync allows credential extraction from AD without touching LSASS. Detected via EventCode 4662 with DS-Replication-Get-Changes and DS-Replication-Get-Changes-All extended rights from a non-DC source. If confirmed, all domain credentials are compromised.' },
    { sep: 'Detection' },
    { type:'relay',  agent:'dl', to:'orch', msg:'2 detection rules drafted · DL-2026-042-001 (T1078.002 privileged logon anomaly) and DL-2026-042-002 (T1003.006 DCSync replication) · back-testing in progress' },
    { type:'reason', agent:'orch', msg:'pipeline in progress — 2 rules in back-test · awaiting results before deployment to Det. Eng.' },
  ],
};

// ── Per-hunt Learn stage data for closed hunts ──
const closedLearnData = {
  '040': {
    reportIcon: '📊', reportTitle: 'FS-ISAC TLP:AMBER — FIN7 Ransomware Precursor Activity',
    reportSource: 'FS-ISAC Sharing Platform', reportDate: 'Apr 24, 2026',
    prioritized: new Set(['T1566.001','T1490']),
    ttps: [
      { id:'T1566.001', name:'Phishing: Spearphishing Attachment', tactic:'Initial Access',   tc:'chip-red',    ph:1, rules:'1 live', reason:'Initial access vector · TA577 IOC confirmed · foundational to kill chain' },
      { id:'T1490',     name:'Inhibit System Recovery',            tactic:'Impact',           tc:'chip-red',    ph:0, rules:'none',   reason:'No detection rule · critical business impact · FIN7 ransomware staging signature' },
      { id:'T1204',     name:'User Execution: Malicious File',     tactic:'Execution',        tc:'chip-indigo', ph:1, rules:'1 live'  },
      { id:'T1486',     name:'Data Encrypted for Impact',          tactic:'Impact',           tc:'chip-red',    ph:0, rules:'none'    },
      { id:'T1574.002', name:'DLL Side-Loading',                   tactic:'Def. Evasion',     tc:'chip-yellow', ph:1, rules:'none'    },
      { id:'T1003.001', name:'OS Credential Dumping: LSASS',       tactic:'Cred. Access',     tc:'chip-red',    ph:2, rules:'1 live'  },
      { id:'T1071.001', name:'Web Protocols C2',                   tactic:'C&amp;C',          tc:'chip-indigo', ph:3, rules:'1 live'  },
      { id:'T1547.001', name:'Registry Run Keys / Startup Folder', tactic:'Persistence',      tc:'chip-indigo', ph:1, rules:'1 live'  },
      { id:'T1053.005', name:'Scheduled Task/Job: Sched. Task',    tactic:'Persistence',      tc:'chip-indigo', ph:1, rules:'1 live'  },
    ],
  },
  '042': {
    reportIcon: '🔐', reportTitle: 'TH-2026-041 Follow-up — Privileged Account Abuse & DCSync Staging',
    reportSource: 'Internal (seeded from TH-2026-041)', reportDate: 'Apr 28, 2026',
    prioritized: new Set(['T1078.002','T1484.001','T1003.006']),
    ttps: [
      { id:'T1078.002', name:'Valid Accounts: Domain Accounts',  tactic:'Def. Evasion',  tc:'chip-red',    ph:0, rules:'1 live',  reason:'jsmith Domain Admin auth on WIN-DC01 · seeded from TH-2026-041 confirmed pivot chain' },
      { id:'T1484.001', name:'Domain Policy Modification',       tactic:'Def. Evasion',  tc:'chip-yellow', ph:0, rules:'none',    reason:'Check for delegation changes or new SPN registrations on Tier-0 accounts' },
      { id:'T1003.006', name:'OS Credential Dumping: DCSync',    tactic:'Cred. Access',  tc:'chip-red',    ph:0, rules:'none',    reason:'DRS replication from non-DC source would mean full domain compromise' },
    ],
  },
  '039': {
    reportIcon: '🏭', reportTitle: 'CISA Advisory — Supply Chain Compromise (SolarWinds-Pattern)',
    reportSource: 'CISA', reportDate: 'Apr 14, 2026',
    prioritized: new Set(['T1195.002','T1071.001']),
    ttps: [
      { id:'T1195.002', name:'Supply Chain Compromise: Software',  tactic:'Initial Access',   tc:'chip-red',    ph:0, rules:'none',   reason:'Root cause · no prior hunt or rule · entire build pipeline exposed' },
      { id:'T1071.001', name:'Web Protocols C2',                   tactic:'C&amp;C',          tc:'chip-indigo', ph:3, rules:'1 live',  reason:'Active C2 indicator · JA3 detection path available · highest immediate risk' },
      { id:'T1574.002', name:'DLL Side-Loading',                   tactic:'Def. Evasion',     tc:'chip-yellow', ph:1, rules:'none'    },
      { id:'T1053.005', name:'Scheduled Task/Job: Sched. Task',    tactic:'Persistence',      tc:'chip-indigo', ph:1, rules:'1 live'  },
      { id:'T1041',     name:'Exfiltration over C2 Channel',       tactic:'Exfiltration',     tc:'chip-red',    ph:0, rules:'none'    },
      { id:'T1547.001', name:'Registry Run Keys / Startup Folder', tactic:'Persistence',      tc:'chip-indigo', ph:1, rules:'1 live'  },
      { id:'T1566.001', name:'Phishing: Spearphishing Attachment', tactic:'Initial Access',   tc:'chip-red',    ph:1, rules:'1 live'  },
    ],
  },
};

// ── Feed data integrity validator ──────────────────────────────────────────
// Runs once at page load. Any entry that references an agent key not present
// in feedAgents / feedAgentColors fires a console.warn immediately, making
// regressions visible without needing to step through the pipeline manually.
// To fix a warning: add the missing key to BOTH feedAgents AND feedAgentColors.
function _validateFeedData() {
  const known = new Set(Object.keys(feedAgents));

  // 1. feedAgents ↔ feedAgentColors must be in sync
  const missingColor = Object.keys(feedAgents).filter(k => !feedAgentColors[k]);
  if (missingColor.length) {
    console.warn('[pipeline] feedAgents ↔ feedAgentColors mismatch — no color entry for:', missingColor.join(', '));
  }

  // 2. Check every entry in a feed array
  function checkEntries(source, entries) {
    entries.forEach((e, i) => {
      if (!e || e.sep) return;
      if (e.agent && !known.has(e.agent)) {
        console.warn(`[pipeline] ${source}[${i}]: agent "${e.agent}" not in feedAgents — will render as generic 🤖 with no colour`);
      }
      if (e.to && !known.has(e.to)) {
        console.warn(`[pipeline] ${source}[${i}]: to "${e.to}" not in feedAgents — relay header will render as generic 🤖 with no colour`);
      }
    });
  }

  // 3. Validate live feed steps and all closed-hunt archives
  Object.entries(feedSteps).forEach(([step, entries]) =>
    checkEntries(`feedSteps[${step}]`, entries));
  Object.entries(closedHuntFeeds).forEach(([hunt, entries]) =>
    checkEntries(`closedHuntFeeds['${hunt}']`, entries));
}
_validateFeedData();

// ── Render stages 2-4 dynamically for non-041 hunts ──
function _renderDynamicStages(keepId, huntId) {
  const kd = (typeof keepData !== 'undefined') ? keepData[keepId] : null;
  const ld = closedLearnData[keepId];
  const subs = kd?.subhunts || [];
  const locks = kd?.subhuntLock || {};
  const cm = (typeof checkHuntMeta !== 'undefined') ? checkHuntMeta[keepId] : null;
  const isActive = cm && cm.active;

  // ── Stage 2: Hypotheses ──
  const s2body = document.querySelector('#stage-2 .card-body');
  if (s2body && subs.length) {
    const statusIcon = s => s === 'confirmed' ? '✅' : s === 'active' ? '🔵' : '⬜';
    const statusChip = s => s === 'confirmed'
      ? '<span class="chip chip-green" style="font-size:10px;">Confirmed</span>'
      : s === 'active'
        ? '<span class="chip chip-blue" style="font-size:10px;">Active</span>'
        : '<span class="chip chip-gray" style="font-size:10px;">Pending</span>';
    const confMap = {};
    // Extract confidence from feed if available
    const feed = closedHuntFeeds[keepId] || [];
    feed.forEach(e => {
      if (e.msg && e.msg.includes('confidence')) {
        subs.forEach(sh => {
          if (e.msg.includes(sh.ttp)) {
            const m = e.msg.match(/confidence (\d+)%/);
            if (m) confMap[sh.ttp] = m[1];
          }
        });
      }
    });

    s2body.innerHTML = `
      <div class="info-bar"><span class="ib-icon">${isActive ? '⚡' : '🔒'}</span><span>${isActive
        ? 'The <b>Hypothesis Agent</b> generated these hunt hypotheses. Detection rules are <b>in testing</b>.'
        : 'The <b>Hypothesis Agent</b> generated these hunt hypotheses. This view is read-only.'}</span></div>
      <div style="display:flex;flex-direction:column;gap:8px;">
        ${subs.map((sh, i) => {
          const lk = locks[sh.id] || {};
          const conf = confMap[sh.ttp] || '—';
          return `<div class="hyp-card" style="cursor:default;">
            <div class="hyp-head">
              <span class="hyp-num">H-0${i+1}</span>
              <div class="hyp-text">${lk.l || sh.name}</div>
            </div>
            <div class="hyp-meta">
              <span class="chip chip-red" style="font-size:10px;">${sh.ttp}</span>
              ${statusChip(sh.status)}
              ${conf !== '—' ? `<span class="chip chip-indigo" style="font-size:10px;">Confidence ${conf}%</span>` : ''}
            </div>
            <div class="hyp-rationale" style="font-size:11px;color:var(--sub);margin-top:4px;">${lk.o || ''}</div>
          </div>`;
        }).join('')}
      </div>`;
  }

  // ── Stage 3: RAA Supervisor Agent ──
  const s3body = document.querySelector('#stage-3 .card-body');
  const s3head = document.querySelector('#stage-3 .card-head');
  if (s3head) {
    // Update header chip to reflect this hunt's hypothesis
    const chipEl = s3head.querySelector('.chip');
    if (chipEl) chipEl.textContent = subs.length ? subs[0].label + ' · Splunk ES' : 'Splunk ES';
  }
  if (s3body && subs.length) {
    // Determine RAA coverage: process-chain and command-line only cover host-based TTPs
    const raaScope = subs.map(sh => {
      const hostBased = ['T1078','T1003','T1059','T1053','T1547','T1570','T1484'].some(p => sh.ttp.startsWith(p));
      return { ...sh, inScope: hostBased };
    });
    s3body.innerHTML = `
      <div class="info-bar"><span class="ib-icon">📌</span><span>The RAA Supervisor Agent queries <b>running analytics</b> against Splunk logs and surfaces hits matching each hypothesis. TTPs with no analytic coverage are passed to the Detection Logic Agent.</span></div>
      <div>
        <div class="label" style="margin-bottom:7px;">Analytic Coverage</div>
        <table class="ttp-table">
          <thead><tr><th>Hypothesis</th><th>TTP</th><th>RAA Analytic</th><th>Status</th></tr></thead>
          <tbody>
            ${raaScope.map(sh => `<tr>
              <td>${sh.label}</td>
              <td class="ttp-id">${sh.ttp}</td>
              <td>${sh.inScope ? 'Process Chain / Command Line' : '<span style="color:var(--muted);">Out of scope</span>'}</td>
              <td>${sh.inScope
                ? '<span class="chip chip-yellow" style="font-size:10px;">Queried</span>'
                : '<span class="chip chip-gray" style="font-size:10px;">→ Detection Logic</span>'}</td>
            </tr>`).join('')}
          </tbody>
        </table>
      </div>
      <div>
        <div class="label" style="margin-bottom:7px;">Coverage Gaps → Detection Logic</div>
        <div style="display:flex;flex-direction:column;gap:5px;font-size:11px;color:var(--sub);">
          ${raaScope.filter(sh => !sh.inScope).map(sh =>
            `<div style="display:flex;align-items:center;gap:8px;"><span class="chip chip-gray" style="font-size:10px;">${sh.ttp}</span>${sh.name} — outside RAA process-chain scope. New SPL rule needed.</div>`
          ).join('') || '<div style="color:var(--green);">All TTPs covered by RAA analytics.</div>'}
        </div>
      </div>`;
  }

  // ── Stage 4: Detection Logic Agent ──
  const s4body = document.querySelector('#stage-4 .card-body');
  if (s4body) {
    // Pull rule info from feed entries
    const feedEntries = closedHuntFeeds[keepId] || [];
    const ruleEntries = feedEntries.filter(e => e.msg && (e.msg.includes('rule') || e.msg.includes('DL-')));
    const ruleMsg = ruleEntries.length ? ruleEntries[ruleEntries.length - 1].msg : '';
    s4body.innerHTML = `
      <div class="info-bar"><span class="ib-icon">${isActive ? '⚡' : '🔒'}</span><span>${isActive
        ? 'Detection rules are <b>in testing</b>. Run queries in the <b>Check</b> tab to validate.'
        : 'Detection rules were generated and validated during this hunt.'}</span></div>
      <div>
        <div class="label" style="margin-bottom:7px;">Rules Generated</div>
        <table class="ttp-table">
          <thead><tr><th>Hypothesis</th><th>TTP</th><th>Rule</th><th>Status</th></tr></thead>
          <tbody>
            ${subs.map((sh, i) => `<tr>
              <td>${sh.label}</td>
              <td class="ttp-id">${sh.ttp}</td>
              <td>DL-${huntId.replace('TH-','')}-00${i+1}</td>
              <td>${isActive
                ? '<span class="chip chip-yellow" style="font-size:10px;">Testing</span>'
                : '<span class="chip chip-green" style="font-size:10px;">Deployed</span>'}</td>
            </tr>`).join('')}
          </tbody>
        </table>
      </div>
      ${ruleMsg ? `<div style="font-size:11px;color:var(--sub);margin-top:8px;padding:8px 10px;background:var(--s2);border-radius:var(--radius-sm);border:1px solid var(--border);">${ruleMsg}</div>` : ''}
      <div style="margin-top:10px;display:flex;justify-content:flex-end;">
        <button class="btn btn-primary btn-sm" onclick="goSubTab('check',document.getElementById('subtab-check'))">Run in Check →</button>
      </div>`;
  }
}

// ── Load pre-baked pipeline state for closed/archived hunts ──
function loadClosedPipeline(huntId, keepId) {
  const cm = (typeof checkHuntMeta !== 'undefined') ? checkHuntMeta[keepId] : null;

  // Update Learn Hunt Context strip
  const lhcHunt  = document.getElementById('lhc-hunt');
  const lhcCti   = document.getElementById('lhc-cti');
  const lhcTtps  = document.getElementById('lhc-ttps');
  const lhcHyp   = document.getElementById('lhc-hyp');
  const lhcStage = document.getElementById('lhc-stage');
  if (lhcHunt)  lhcHunt.textContent  = huntId;
  if (lhcCti)   lhcCti.textContent   = cm ? cm.cti : '';
  if (lhcTtps)  lhcTtps.textContent  = cm ? cm.ttpCount : '';
  const isActive = cm && cm.active;
  if (lhcHyp)   { lhcHyp.textContent = cm ? cm.hypCount : '2 confirmed'; lhcHyp.style.color = ''; }
  if (lhcStage) lhcStage.textContent = isActive ? 'Learn · Check' : 'Learn · Detection';

  // Show context panel + agents card
  const ctxPanel  = document.getElementById('learn-hunt-context');
  const agentCard = document.getElementById('learn-agents-card');
  if (ctxPanel)  ctxPanel.style.display  = '';
  if (agentCard) agentCard.style.display = '';

  // Update stage1-report-chips
  const chips = document.getElementById('stage1-report-chips');
  if (chips && cm) {
    const parts      = cm.ttpCount.split(' · ');
    const extracted  = parts[0] || cm.ttpCount;
    const prioritized = parts[1] || '';
    chips.innerHTML  = `<span class="chip chip-blue">${extracted}</span>`
                     + (prioritized ? `<span class="chip chip-indigo">${prioritized}</span>` : '')
                     + `<span class="chip chip-indigo">ATT&amp;CK v14</span>`;
  }

  // Advance pipeline bar to fully completed state (silent — no streaming)
  const is041 = keepId === '041';
  maxStep = 4;
  for (let j = 0; j < 5; j++) {
    const n = document.getElementById('ps' + j);
    if (n) n.className = 'ps-node done';
    if (j < 4) {
      const l = document.getElementById('pl' + j);
      if (l) l.className = 'ps-line done';
    }
    const s = document.getElementById('stage-' + j);
    if (s) s.className = 'stage card show';
  }

  // For non-041 hunts, dynamically render stages 2-4 from hunt data
  if (!is041) _renderDynamicStages(keepId, huntId);

  // Hide/show TTP selection buttons (only interactive for 041 live pipeline)
  const ttpBtnBar = document.getElementById('ttp-btn-bar');
  if (ttpBtnBar) {
    if (!is041) { ttpBtnBar.setAttribute('data-archived-hidden', '1'); ttpBtnBar.style.display = 'none'; }
    else        { ttpBtnBar.removeAttribute('data-archived-hidden'); ttpBtnBar.style.display = ''; }
  }

  updateAgentPills(4);
  for (let i = 0; i < 5; i++) _setAgentProgStep(i, 'done');
  ['orch','hyp','data','ts','dl'].forEach(a => _setAgentLegendStatus(a, 'done'));

  // Show past hunts card
  const pastCard = document.getElementById('learn-past-card');
  if (pastCard) pastCard.style.display = '';

  // Feed status
  const feedStatus = document.getElementById('feed-status');
  if (feedStatus) feedStatus.textContent = isActive ? 'in progress' : 'archived';
  const dot      = document.getElementById('agents-feed-dot');
  const agStatus = document.getElementById('agents-feed-status');
  if (dot)      dot.style.opacity     = isActive ? '1' : '0.35';
  if (agStatus) agStatus.textContent  = (isActive ? 'running · ' : 'archived · ') + huntId;

  // Populate feed with pre-baked entries (no typewriter)
  const entries = closedHuntFeeds[keepId] || [];
  entries.forEach(e => {
    if (e.sep) feedAddBlockSep(e.sep);
    else feedAddBlock(e, false);
  });

  // Approximate token count for visual consistency
  const tokEl = document.getElementById('feed-token-count');
  if (tokEl) {
    tokEl.style.display = '';
    const tokCounts = { '040': '~8,400 tok', '039': '~7,100 tok', '042': '~4,200 tok' };
    tokEl.textContent = tokCounts[keepId] || '~6,000 tok';
  }

  // ── Lock pipeline stepper ──
  // Active hunts: gate Keep tab (maxStep=3 unlocks Observe+Check only)
  // Closed hunts: unlock all tabs
  if (isActive) {
    pipelineLocked = false;
    maxStep = 3;
  } else {
    pipelineLocked = true;
  }
  if (typeof updateSubTabGating === 'function') updateSubTabGating();
  const pipelineEl = document.querySelector('.pipeline');
  if (pipelineEl) pipelineEl.classList.add('pipeline-locked');

  // ── Stage 0: archived report card ──
  const ld = closedLearnData[keepId];
  if (ld) {
    // Summary bar
    const s0sum = document.getElementById('stage-0-summary-text');
    if (s0sum) s0sum.innerHTML = `${ld.reportIcon} <b>${ld.reportTitle}</b> · <span style="color:var(--green);font-weight:600;">${ld.ttps.length} TTPs</span> · ${ld.reportSource}`;

    // Replace info-bar with archived notice, hide search, replace repo list
    const s0body = document.querySelector('#stage-0 .card-body');
    if (s0body) {
      // Archived notice replaces the old info-bar
      const oldInfoBar = s0body.querySelector('.info-bar');
      if (oldInfoBar) oldInfoBar.innerHTML = isActive
        ? `<span class="ib-icon">⚡</span><span>This hunt is <b>active</b>. TTPs have been extracted and hypotheses generated. Detection rules are <b>in testing</b> — check the <b>Check</b> tab for query results.</span>`
        : `<span class="ib-icon">🔒</span><span>This hunt is <b>closed and archived</b>. The intelligence report and TTP selection are locked. View the <b>Keep</b> tab for the final hunt record.</span>`;

      // Hide repo search (marked for restoration)
      const srchWrap = s0body.querySelector('.repo-search-wrap');
      if (srchWrap) { srchWrap.setAttribute('data-archived-hidden', '1'); srchWrap.style.display = 'none'; }

      // Replace repo list with a single archived report card
      const repoList = document.getElementById('repo-list');
      if (repoList) {
        repoList.innerHTML = `
          <div class="repo-archived-card">
            <div class="rac-icon">${ld.reportIcon}</div>
            <div class="rac-info">
              <div class="rac-title">${ld.reportTitle}</div>
              <div class="rac-meta">
                <span>${ld.reportSource}</span>
                <span style="color:var(--border2);">·</span>
                <span>${ld.ttps.length} TTPs extracted</span>
                <span style="color:var(--border2);">·</span>
                <span>${ld.reportDate}</span>
              </div>
            </div>
            <span class="chip chip-green" style="flex-shrink:0;">✓ Archived</span>
          </div>`;
      }

      // Hide the "Start with custom TTPs" footer row (marked for restoration)
      const customFooter = s0body.querySelector('div[style*="border-top"]');
      if (customFooter) { customFooter.setAttribute('data-archived-hidden', '1'); customFooter.style.display = 'none'; }
    }
  }

  // ── Stage 1: per-hunt TTP table with prioritized rows highlighted ──
  if (ld) {
    const tbody = document.getElementById('ttp-tbody');
    if (tbody) {
      const phColor = n => n >= 2 ? 'var(--green)' : n === 1 ? 'var(--yellow)' : 'var(--muted)';
      tbody.innerHTML = ld.ttps.map(t => {
        const isPri = ld.prioritized.has(t.id);
        const idCell = isPri
          ? `<td class="ttp-id">${t.id}<span class="ttp-pri-badge">🎯 Selected</span></td>`
          : `<td class="ttp-id">${t.id}</td>`;
        const nameCell = isPri && t.reason
          ? `<td>${t.name}<br><span style="font-size:10px;color:var(--blue);margin-top:2px;display:block;">${t.reason}</span></td>`
          : `<td>${t.name}</td>`;
        return `<tr class="${isPri ? 'ttp-row-prioritized' : ''}">
          <td class="ttp-sel-col">${isPri ? '<span style="color:var(--green);">☑</span>' : ''}</td>
          ${idCell}
          ${nameCell}
          <td><span class="chip ${t.tc}">${t.tactic}</span></td>
          <td style="font-size:11px;color:${phColor(t.ph)};font-weight:600;">${t.ph || 0}</td>
          <td style="font-size:11px;color:${t.rules === 'none' ? 'var(--muted)' : 'var(--green)'};font-weight:600;">${t.rules}</td>
          <td>—</td>
        </tr>`;
      }).join('');
    }

    // Hide custom TTP add form (marked for restoration)
    const customWrap = document.getElementById('custom-ttp-wrap');
    if (customWrap) { customWrap.setAttribute('data-archived-hidden', '1'); customWrap.style.display = 'none'; }
    // Hide gate-1 for non-041 hunts (041-specific content; dynamic stages replace it)
    const gate1 = document.getElementById('gate-1');
    if (gate1 && !is041) { gate1.setAttribute('data-archived-hidden', '1'); gate1.style.display = 'none'; }
    if (gate1 && is041)  { gate1.removeAttribute('data-archived-hidden'); gate1.style.display = ''; }

    // Update the Stage 1 info-bar to reflect state
    const s1InfoBar = document.querySelector('#stage-1 .info-bar');
    if (s1InfoBar) s1InfoBar.innerHTML = isActive
      ? `<span class="ib-icon">⚡</span><span>TTPs extracted and hypotheses generated. <b>Highlighted rows</b> (🎯) were selected for hypothesis generation. Detection rules are now <b>in testing</b>.</span>`
      : `<span class="ib-icon">🔒</span><span>TTPs were extracted and prioritized during this hunt. <b>Highlighted rows</b> (🎯) were selected for hypothesis generation. This view is read-only — see the <b>Keep</b> tab for the full hunt record.</span>`;
  }

  // Reveal subhunt sidebar (was hidden by resetPipeline; now hypotheses are loaded)
  if (typeof renderSubhuntSidebar === 'function') {
    renderSubhuntSidebar(huntId);
  }
}

// ── Capture original Stage 0 / Stage 1 content for restoration on hunt switch ──
;(function() {
  const tb   = document.getElementById('ttp-tbody');
  const s0ib = document.querySelector('#stage-0 .info-bar');
  const s1ib = document.querySelector('#stage-1 .info-bar');
  if (tb)   _origTtpTbody      = tb.innerHTML;
  if (s0ib) _origStage0InfoBar = s0ib.innerHTML;
  if (s1ib) _origStage1InfoBar = s1ib.innerHTML;
})();
